########### TODO ################
# TODO- Hacer otro  módulo para modificar los pedidos y agregar los documentos faltantes
########### TODO ################
#convertir QT a PYthon
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from Detalle_pedido_3 import *
from pathlib import Path
from datetime import date, datetime
from ALTAPEDIDOS_3 import *
from Detalle_pedido_3 import *
import subprocess
import dateutil.parser as dp
import logging
import sqlite3
import json
import time
import sys
import os
import os.path
import shutil
# Enable logging
logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',level=logging.INFO)
logger = logging.getLogger(__name__)
# Enable logging
basedatos='administrativo.db'
#Globales#
pagina=int(0)
vectorglobal=[]
#


class Ui_Gestor_Pedidos(object):
    def ALTAPEDIDOS(self): #NO USAR
        script = "ALTAPEDIDOS_3.py"
        # os.system(script)
        subprocess.Popen([sys.executable, script], stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT)
        sys.exit()
        return ()
    def nuevacotizacion(self): #NO USAR
        script = "COTIZADOR_1_2_1.py"
        # os.system(script)
        subprocess.Popen([sys.executable, script], stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT)
        sys.exit()
        return ()

    def setupUi(self, Gestor_Pedidos):
        Gestor_Pedidos.setObjectName("Gestor_Pedidos")
        Gestor_Pedidos.setEnabled(True)
        Gestor_Pedidos.resize(842, 549)
        Gestor_Pedidos.setMinimumSize(QtCore.QSize(836, 533))
        Gestor_Pedidos.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(Gestor_Pedidos)
        self.centralwidget.setObjectName("centralwidget")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(10, 160, 25, 19))
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(10, 190, 25, 19))
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_3.setGeometry(QtCore.QRect(10, 220, 25, 19))
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_4.setGeometry(QtCore.QRect(10, 250, 25, 19))
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_5.setGeometry(QtCore.QRect(10, 280, 25, 19))
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_6 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_6.setGeometry(QtCore.QRect(10, 310, 25, 19))
        self.toolButton_6.setObjectName("toolButton_6")
        self.toolButton_7 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_7.setGeometry(QtCore.QRect(10, 340, 25, 19))
        self.toolButton_7.setObjectName("toolButton_7")
        self.toolButton_8 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_8.setGeometry(QtCore.QRect(10, 370, 25, 19))
        self.toolButton_8.setObjectName("toolButton_8")
        self.toolButton_9 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_9.setGeometry(QtCore.QRect(10, 400, 25, 19))
        self.toolButton_9.setObjectName("toolButton_9")
        self.toolButton_10 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_10.setGeometry(QtCore.QRect(10, 430, 25, 19))
        self.toolButton_10.setObjectName("toolButton_10")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 130, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 130, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 130, 161, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 130, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(520, 130, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(620, 130, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(690, 120, 61, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(770, 120, 61, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(90, 140, 20, 321))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(150, 140, 20, 321))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(330, 140, 20, 321))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(500, 140, 20, 321))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(590, 140, 20, 321))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(670, 140, 20, 321))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(750, 140, 20, 321))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(30, 130, 20, 331))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_20 = QtWidgets.QFrame(self.centralwidget)
        self.line_20.setGeometry(QtCore.QRect(830, 140, 20, 321))
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.PED_1 = QtWidgets.QLabel(self.centralwidget)
        self.PED_1.setGeometry(QtCore.QRect(40, 160, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.PED_1.setFont(font)
        self.PED_1.setText("")
        self.PED_1.setObjectName("PED_1")
        self.PED_2 = QtWidgets.QLabel(self.centralwidget)
        self.PED_2.setGeometry(QtCore.QRect(40, 190, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.PED_2.setFont(font)
        self.PED_2.setText("")
        self.PED_2.setObjectName("PED_2")
        self.PED_3 = QtWidgets.QLabel(self.centralwidget)
        self.PED_3.setGeometry(QtCore.QRect(40, 220, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.PED_3.setFont(font)
        self.PED_3.setText("")
        self.PED_3.setObjectName("PED_3")
        self.PED_4 = QtWidgets.QLabel(self.centralwidget)
        self.PED_4.setGeometry(QtCore.QRect(40, 250, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.PED_4.setFont(font)
        self.PED_4.setText("")
        self.PED_4.setObjectName("PED_4")
        self.PED_5 = QtWidgets.QLabel(self.centralwidget)
        self.PED_5.setGeometry(QtCore.QRect(40, 280, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.PED_5.setFont(font)
        self.PED_5.setText("")
        self.PED_5.setObjectName("PED_5")
        self.PED_6 = QtWidgets.QLabel(self.centralwidget)
        self.PED_6.setGeometry(QtCore.QRect(40, 310, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.PED_6.setFont(font)
        self.PED_6.setText("")
        self.PED_6.setObjectName("PED_6")
        self.PED_7 = QtWidgets.QLabel(self.centralwidget)
        self.PED_7.setGeometry(QtCore.QRect(40, 340, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.PED_7.setFont(font)
        self.PED_7.setText("")
        self.PED_7.setObjectName("PED_7")
        self.PED_8 = QtWidgets.QLabel(self.centralwidget)
        self.PED_8.setGeometry(QtCore.QRect(40, 370, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.PED_8.setFont(font)
        self.PED_8.setText("")
        self.PED_8.setObjectName("PED_8")
        self.PED_9 = QtWidgets.QLabel(self.centralwidget)
        self.PED_9.setGeometry(QtCore.QRect(40, 400, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.PED_9.setFont(font)
        self.PED_9.setText("")
        self.PED_9.setObjectName("PED_9")
        self.PED_10 = QtWidgets.QLabel(self.centralwidget)
        self.PED_10.setGeometry(QtCore.QRect(40, 430, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.PED_10.setFont(font)
        self.PED_10.setText("")
        self.PED_10.setObjectName("PED_10")
        self.TIENDA_1 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_1.setGeometry(QtCore.QRect(110, 160, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_1.setFont(font)
        self.TIENDA_1.setText("")
        self.TIENDA_1.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_1.setObjectName("TIENDA_1")
        self.TIENDA_2 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_2.setGeometry(QtCore.QRect(110, 190, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_2.setFont(font)
        self.TIENDA_2.setText("")
        self.TIENDA_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_2.setObjectName("TIENDA_2")
        self.TIENDA_3 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_3.setGeometry(QtCore.QRect(110, 220, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_3.setFont(font)
        self.TIENDA_3.setText("")
        self.TIENDA_3.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_3.setObjectName("TIENDA_3")
        self.TIENDA_4 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_4.setGeometry(QtCore.QRect(110, 250, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_4.setFont(font)
        self.TIENDA_4.setText("")
        self.TIENDA_4.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_4.setObjectName("TIENDA_4")
        self.TIENDA_5 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_5.setGeometry(QtCore.QRect(110, 280, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_5.setFont(font)
        self.TIENDA_5.setText("")
        self.TIENDA_5.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_5.setObjectName("TIENDA_5")
        self.TIENDA_6 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_6.setGeometry(QtCore.QRect(110, 310, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_6.setFont(font)
        self.TIENDA_6.setText("")
        self.TIENDA_6.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_6.setObjectName("TIENDA_6")
        self.TIENDA_7 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_7.setGeometry(QtCore.QRect(110, 340, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_7.setFont(font)
        self.TIENDA_7.setText("")
        self.TIENDA_7.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_7.setObjectName("TIENDA_7")
        self.TIENDA_8 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_8.setGeometry(QtCore.QRect(110, 370, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_8.setFont(font)
        self.TIENDA_8.setText("")
        self.TIENDA_8.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_8.setObjectName("TIENDA_8")
        self.TIENDA_9 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_9.setGeometry(QtCore.QRect(110, 400, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_9.setFont(font)
        self.TIENDA_9.setText("")
        self.TIENDA_9.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_9.setObjectName("TIENDA_9")
        self.TIENDA_10 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_10.setGeometry(QtCore.QRect(110, 430, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_10.setFont(font)
        self.TIENDA_10.setText("")
        self.TIENDA_10.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_10.setObjectName("TIENDA_10")
        self.COT_1 = QtWidgets.QLabel(self.centralwidget)
        self.COT_1.setGeometry(QtCore.QRect(340, 160, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_1.setFont(font)
        self.COT_1.setText("")
        self.COT_1.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_1.setObjectName("COT_1")
        self.COT_2 = QtWidgets.QLabel(self.centralwidget)
        self.COT_2.setGeometry(QtCore.QRect(340, 190, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_2.setFont(font)
        self.COT_2.setText("")
        self.COT_2.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_2.setObjectName("COT_2")
        self.COT_3 = QtWidgets.QLabel(self.centralwidget)
        self.COT_3.setGeometry(QtCore.QRect(340, 220, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_3.setFont(font)
        self.COT_3.setText("")
        self.COT_3.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_3.setObjectName("COT_3")
        self.COT_4 = QtWidgets.QLabel(self.centralwidget)
        self.COT_4.setGeometry(QtCore.QRect(340, 250, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_4.setFont(font)
        self.COT_4.setText("")
        self.COT_4.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_4.setObjectName("COT_4")
        self.COT_5 = QtWidgets.QLabel(self.centralwidget)
        self.COT_5.setGeometry(QtCore.QRect(340, 280, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_5.setFont(font)
        self.COT_5.setText("")
        self.COT_5.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_5.setObjectName("COT_5")
        self.COT_6 = QtWidgets.QLabel(self.centralwidget)
        self.COT_6.setGeometry(QtCore.QRect(340, 310, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_6.setFont(font)
        self.COT_6.setText("")
        self.COT_6.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_6.setObjectName("COT_6")
        self.COT_7 = QtWidgets.QLabel(self.centralwidget)
        self.COT_7.setGeometry(QtCore.QRect(340, 340, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_7.setFont(font)
        self.COT_7.setText("")
        self.COT_7.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_7.setObjectName("COT_7")
        self.COT_8 = QtWidgets.QLabel(self.centralwidget)
        self.COT_8.setGeometry(QtCore.QRect(340, 370, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_8.setFont(font)
        self.COT_8.setText("")
        self.COT_8.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_8.setObjectName("COT_8")
        self.COT_9 = QtWidgets.QLabel(self.centralwidget)
        self.COT_9.setGeometry(QtCore.QRect(340, 400, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_9.setFont(font)
        self.COT_9.setText("")
        self.COT_9.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_9.setObjectName("COT_9")
        self.COT_10 = QtWidgets.QLabel(self.centralwidget)
        self.COT_10.setGeometry(QtCore.QRect(340, 430, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_10.setFont(font)
        self.COT_10.setText("")
        self.COT_10.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_10.setObjectName("COT_10")
        self.STATS_1 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_1.setGeometry(QtCore.QRect(510, 160, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_1.setFont(font)
        self.STATS_1.setText("")
        self.STATS_1.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_1.setObjectName("STATS_1")
        self.STATS_2 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_2.setGeometry(QtCore.QRect(510, 190, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_2.setFont(font)
        self.STATS_2.setText("")
        self.STATS_2.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_2.setObjectName("STATS_2")
        self.STATS_3 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_3.setGeometry(QtCore.QRect(510, 220, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_3.setFont(font)
        self.STATS_3.setText("")
        self.STATS_3.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_3.setObjectName("STATS_3")
        self.STATS_4 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_4.setGeometry(QtCore.QRect(510, 250, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_4.setFont(font)
        self.STATS_4.setText("")
        self.STATS_4.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_4.setObjectName("STATS_4")
        self.STATS_5 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_5.setGeometry(QtCore.QRect(510, 280, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_5.setFont(font)
        self.STATS_5.setText("")
        self.STATS_5.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_5.setObjectName("STATS_5")
        self.STATS_6 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_6.setGeometry(QtCore.QRect(510, 310, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_6.setFont(font)
        self.STATS_6.setText("")
        self.STATS_6.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_6.setObjectName("STATS_6")
        self.STATS_7 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_7.setGeometry(QtCore.QRect(510, 340, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_7.setFont(font)
        self.STATS_7.setText("")
        self.STATS_7.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_7.setObjectName("STATS_7")
        self.STATS_8 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_8.setGeometry(QtCore.QRect(510, 370, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_8.setFont(font)
        self.STATS_8.setText("")
        self.STATS_8.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_8.setObjectName("STATS_8")
        self.STATS_9 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_9.setGeometry(QtCore.QRect(510, 400, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_9.setFont(font)
        self.STATS_9.setText("")
        self.STATS_9.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_9.setObjectName("STATS_9")
        self.STATS_10 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_10.setGeometry(QtCore.QRect(510, 430, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_10.setFont(font)
        self.STATS_10.setText("")
        self.STATS_10.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_10.setObjectName("STATS_10")
        self.DOCS_1 = QtWidgets.QLabel(self.centralwidget)
        self.DOCS_1.setGeometry(QtCore.QRect(610, 160, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.DOCS_1.setFont(font)
        self.DOCS_1.setText("")
        self.DOCS_1.setAlignment(QtCore.Qt.AlignCenter)
        self.DOCS_1.setObjectName("DOCS_1")
        self.DOCS_2 = QtWidgets.QLabel(self.centralwidget)
        self.DOCS_2.setGeometry(QtCore.QRect(610, 190, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.DOCS_2.setFont(font)
        self.DOCS_2.setText("")
        self.DOCS_2.setAlignment(QtCore.Qt.AlignCenter)
        self.DOCS_2.setObjectName("DOCS_2")
        self.DOCS_3 = QtWidgets.QLabel(self.centralwidget)
        self.DOCS_3.setGeometry(QtCore.QRect(610, 220, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.DOCS_3.setFont(font)
        self.DOCS_3.setText("")
        self.DOCS_3.setAlignment(QtCore.Qt.AlignCenter)
        self.DOCS_3.setObjectName("DOCS_3")
        self.DOCS_4 = QtWidgets.QLabel(self.centralwidget)
        self.DOCS_4.setGeometry(QtCore.QRect(610, 250, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.DOCS_4.setFont(font)
        self.DOCS_4.setText("")
        self.DOCS_4.setAlignment(QtCore.Qt.AlignCenter)
        self.DOCS_4.setObjectName("DOCS_4")
        self.DOCS_5 = QtWidgets.QLabel(self.centralwidget)
        self.DOCS_5.setGeometry(QtCore.QRect(610, 280, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.DOCS_5.setFont(font)
        self.DOCS_5.setText("")
        self.DOCS_5.setAlignment(QtCore.Qt.AlignCenter)
        self.DOCS_5.setObjectName("DOCS_5")
        self.DOCS_6 = QtWidgets.QLabel(self.centralwidget)
        self.DOCS_6.setGeometry(QtCore.QRect(610, 310, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.DOCS_6.setFont(font)
        self.DOCS_6.setText("")
        self.DOCS_6.setAlignment(QtCore.Qt.AlignCenter)
        self.DOCS_6.setObjectName("DOCS_6")
        self.DOCS_7 = QtWidgets.QLabel(self.centralwidget)
        self.DOCS_7.setGeometry(QtCore.QRect(610, 340, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.DOCS_7.setFont(font)
        self.DOCS_7.setText("")
        self.DOCS_7.setAlignment(QtCore.Qt.AlignCenter)
        self.DOCS_7.setObjectName("DOCS_7")
        self.DOCS_8 = QtWidgets.QLabel(self.centralwidget)
        self.DOCS_8.setGeometry(QtCore.QRect(610, 370, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.DOCS_8.setFont(font)
        self.DOCS_8.setText("")
        self.DOCS_8.setAlignment(QtCore.Qt.AlignCenter)
        self.DOCS_8.setObjectName("DOCS_8")
        self.DOCS_9 = QtWidgets.QLabel(self.centralwidget)
        self.DOCS_9.setGeometry(QtCore.QRect(610, 400, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.DOCS_9.setFont(font)
        self.DOCS_9.setText("")
        self.DOCS_9.setAlignment(QtCore.Qt.AlignCenter)
        self.DOCS_9.setObjectName("DOCS_9")
        self.DOCS_10 = QtWidgets.QLabel(self.centralwidget)
        self.DOCS_10.setGeometry(QtCore.QRect(610, 430, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.DOCS_10.setFont(font)
        self.DOCS_10.setText("")
        self.DOCS_10.setAlignment(QtCore.Qt.AlignCenter)
        self.DOCS_10.setObjectName("DOCS_10")
        self.IEMBARQUE_1 = QtWidgets.QLabel(self.centralwidget)
        self.IEMBARQUE_1.setGeometry(QtCore.QRect(680, 160, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.IEMBARQUE_1.setFont(font)
        self.IEMBARQUE_1.setText("")
        self.IEMBARQUE_1.setAlignment(QtCore.Qt.AlignCenter)
        self.IEMBARQUE_1.setObjectName("IEMBARQUE_1")
        self.IEMBARQUE_2 = QtWidgets.QLabel(self.centralwidget)
        self.IEMBARQUE_2.setGeometry(QtCore.QRect(680, 190, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.IEMBARQUE_2.setFont(font)
        self.IEMBARQUE_2.setText("")
        self.IEMBARQUE_2.setAlignment(QtCore.Qt.AlignCenter)
        self.IEMBARQUE_2.setObjectName("IEMBARQUE_2")
        self.IEMBARQUE_3 = QtWidgets.QLabel(self.centralwidget)
        self.IEMBARQUE_3.setGeometry(QtCore.QRect(680, 220, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.IEMBARQUE_3.setFont(font)
        self.IEMBARQUE_3.setText("")
        self.IEMBARQUE_3.setAlignment(QtCore.Qt.AlignCenter)
        self.IEMBARQUE_3.setObjectName("IEMBARQUE_3")
        self.IEMBARQUE_4 = QtWidgets.QLabel(self.centralwidget)
        self.IEMBARQUE_4.setGeometry(QtCore.QRect(680, 250, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.IEMBARQUE_4.setFont(font)
        self.IEMBARQUE_4.setText("")
        self.IEMBARQUE_4.setAlignment(QtCore.Qt.AlignCenter)
        self.IEMBARQUE_4.setObjectName("IEMBARQUE_4")
        self.IEMBARQUE_5 = QtWidgets.QLabel(self.centralwidget)
        self.IEMBARQUE_5.setGeometry(QtCore.QRect(680, 280, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.IEMBARQUE_5.setFont(font)
        self.IEMBARQUE_5.setText("")
        self.IEMBARQUE_5.setAlignment(QtCore.Qt.AlignCenter)
        self.IEMBARQUE_5.setObjectName("IEMBARQUE_5")
        self.IEMBARQUE_6 = QtWidgets.QLabel(self.centralwidget)
        self.IEMBARQUE_6.setGeometry(QtCore.QRect(680, 310, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.IEMBARQUE_6.setFont(font)
        self.IEMBARQUE_6.setText("")
        self.IEMBARQUE_6.setAlignment(QtCore.Qt.AlignCenter)
        self.IEMBARQUE_6.setObjectName("IEMBARQUE_6")
        self.IEMBARQUE_7 = QtWidgets.QLabel(self.centralwidget)
        self.IEMBARQUE_7.setGeometry(QtCore.QRect(680, 340, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.IEMBARQUE_7.setFont(font)
        self.IEMBARQUE_7.setText("")
        self.IEMBARQUE_7.setAlignment(QtCore.Qt.AlignCenter)
        self.IEMBARQUE_7.setObjectName("IEMBARQUE_7")
        self.IEMBARQUE_8 = QtWidgets.QLabel(self.centralwidget)
        self.IEMBARQUE_8.setGeometry(QtCore.QRect(680, 370, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.IEMBARQUE_8.setFont(font)
        self.IEMBARQUE_8.setText("")
        self.IEMBARQUE_8.setAlignment(QtCore.Qt.AlignCenter)
        self.IEMBARQUE_8.setObjectName("IEMBARQUE_8")
        self.IEMBARQUE_9 = QtWidgets.QLabel(self.centralwidget)
        self.IEMBARQUE_9.setGeometry(QtCore.QRect(680, 400, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.IEMBARQUE_9.setFont(font)
        self.IEMBARQUE_9.setText("")
        self.IEMBARQUE_9.setAlignment(QtCore.Qt.AlignCenter)
        self.IEMBARQUE_9.setObjectName("IEMBARQUE_9")
        self.IEMBARQUE_10 = QtWidgets.QLabel(self.centralwidget)
        self.IEMBARQUE_10.setGeometry(QtCore.QRect(680, 430, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.IEMBARQUE_10.setFont(font)
        self.IEMBARQUE_10.setText("")
        self.IEMBARQUE_10.setAlignment(QtCore.Qt.AlignCenter)
        self.IEMBARQUE_10.setObjectName("IEMBARQUE_10")
        self.ENTREGA_1 = QtWidgets.QLabel(self.centralwidget)
        self.ENTREGA_1.setGeometry(QtCore.QRect(760, 160, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.ENTREGA_1.setFont(font)
        self.ENTREGA_1.setText("")
        self.ENTREGA_1.setAlignment(QtCore.Qt.AlignCenter)
        self.ENTREGA_1.setObjectName("ENTREGA_1")
        self.ENTREGA_2 = QtWidgets.QLabel(self.centralwidget)
        self.ENTREGA_2.setGeometry(QtCore.QRect(760, 190, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.ENTREGA_2.setFont(font)
        self.ENTREGA_2.setText("")
        self.ENTREGA_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ENTREGA_2.setObjectName("ENTREGA_2")
        self.ENTREGA_3 = QtWidgets.QLabel(self.centralwidget)
        self.ENTREGA_3.setGeometry(QtCore.QRect(760, 220, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.ENTREGA_3.setFont(font)
        self.ENTREGA_3.setText("")
        self.ENTREGA_3.setAlignment(QtCore.Qt.AlignCenter)
        self.ENTREGA_3.setObjectName("ENTREGA_3")
        self.ENTREGA_4 = QtWidgets.QLabel(self.centralwidget)
        self.ENTREGA_4.setGeometry(QtCore.QRect(760, 250, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.ENTREGA_4.setFont(font)
        self.ENTREGA_4.setText("")
        self.ENTREGA_4.setAlignment(QtCore.Qt.AlignCenter)
        self.ENTREGA_4.setObjectName("ENTREGA_4")
        self.ENTREGA_5 = QtWidgets.QLabel(self.centralwidget)
        self.ENTREGA_5.setGeometry(QtCore.QRect(760, 280, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.ENTREGA_5.setFont(font)
        self.ENTREGA_5.setText("")
        self.ENTREGA_5.setAlignment(QtCore.Qt.AlignCenter)
        self.ENTREGA_5.setObjectName("ENTREGA_5")
        self.ENTREGA_6 = QtWidgets.QLabel(self.centralwidget)
        self.ENTREGA_6.setGeometry(QtCore.QRect(760, 310, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.ENTREGA_6.setFont(font)
        self.ENTREGA_6.setText("")
        self.ENTREGA_6.setAlignment(QtCore.Qt.AlignCenter)
        self.ENTREGA_6.setObjectName("ENTREGA_6")
        self.ENTREGA_7 = QtWidgets.QLabel(self.centralwidget)
        self.ENTREGA_7.setGeometry(QtCore.QRect(760, 340, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.ENTREGA_7.setFont(font)
        self.ENTREGA_7.setText("")
        self.ENTREGA_7.setAlignment(QtCore.Qt.AlignCenter)
        self.ENTREGA_7.setObjectName("ENTREGA_7")
        self.ENTREGA_8 = QtWidgets.QLabel(self.centralwidget)
        self.ENTREGA_8.setGeometry(QtCore.QRect(760, 370, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.ENTREGA_8.setFont(font)
        self.ENTREGA_8.setText("")
        self.ENTREGA_8.setAlignment(QtCore.Qt.AlignCenter)
        self.ENTREGA_8.setObjectName("ENTREGA_8")
        self.ENTREGA_9 = QtWidgets.QLabel(self.centralwidget)
        self.ENTREGA_9.setGeometry(QtCore.QRect(760, 400, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.ENTREGA_9.setFont(font)
        self.ENTREGA_9.setText("")
        self.ENTREGA_9.setAlignment(QtCore.Qt.AlignCenter)
        self.ENTREGA_9.setObjectName("ENTREGA_9")
        self.ENTREGA_10 = QtWidgets.QLabel(self.centralwidget)
        self.ENTREGA_10.setGeometry(QtCore.QRect(760, 430, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.ENTREGA_10.setFont(font)
        self.ENTREGA_10.setText("")
        self.ENTREGA_10.setAlignment(QtCore.Qt.AlignCenter)
        self.ENTREGA_10.setObjectName("ENTREGA_10")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(40, 150, 801, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_8.setFont(font)
        self.line_8.setLineWidth(1)
        self.line_8.setMidLineWidth(1)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(40, 180, 801, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_9.setFont(font)
        self.line_9.setLineWidth(1)
        self.line_9.setMidLineWidth(1)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(40, 210, 801, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_10.setFont(font)
        self.line_10.setLineWidth(1)
        self.line_10.setMidLineWidth(1)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(40, 240, 801, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_11.setFont(font)
        self.line_11.setLineWidth(1)
        self.line_11.setMidLineWidth(1)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(40, 270, 801, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_12.setFont(font)
        self.line_12.setLineWidth(1)
        self.line_12.setMidLineWidth(1)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(40, 300, 801, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_13.setFont(font)
        self.line_13.setLineWidth(1)
        self.line_13.setMidLineWidth(1)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(40, 330, 801, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_14.setFont(font)
        self.line_14.setLineWidth(1)
        self.line_14.setMidLineWidth(1)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(40, 360, 801, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_15.setFont(font)
        self.line_15.setLineWidth(1)
        self.line_15.setMidLineWidth(1)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(40, 390, 801, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_16.setFont(font)
        self.line_16.setLineWidth(1)
        self.line_16.setMidLineWidth(1)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(40, 420, 801, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_17.setFont(font)
        self.line_17.setLineWidth(1)
        self.line_17.setMidLineWidth(1)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(40, 450, 801, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_19.setFont(font)
        self.line_19.setLineWidth(1)
        self.line_19.setMidLineWidth(1)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.ADELANTE = QtWidgets.QPushButton(self.centralwidget)
        self.ADELANTE.setGeometry(QtCore.QRect(620, 10, 41, 31))
        self.ADELANTE.setObjectName("ADELANTE")
        self.TITULO_1 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_1.setGeometry(QtCore.QRect(160, 160, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_1.setFont(font)
        self.TITULO_1.setText("")
        self.TITULO_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_1.setObjectName("TITULO_1")
        self.TITULO_2 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_2.setGeometry(QtCore.QRect(160, 190, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_2.setFont(font)
        self.TITULO_2.setText("")
        self.TITULO_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_2.setObjectName("TITULO_2")
        self.TITULO_3 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_3.setGeometry(QtCore.QRect(160, 220, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_3.setFont(font)
        self.TITULO_3.setText("")
        self.TITULO_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_3.setObjectName("TITULO_3")
        self.TITULO_4 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_4.setGeometry(QtCore.QRect(160, 250, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_4.setFont(font)
        self.TITULO_4.setText("")
        self.TITULO_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_4.setObjectName("TITULO_4")
        self.TITULO_5 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_5.setGeometry(QtCore.QRect(160, 280, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_5.setFont(font)
        self.TITULO_5.setText("")
        self.TITULO_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_5.setObjectName("TITULO_5")
        self.TITULO_6 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_6.setGeometry(QtCore.QRect(160, 310, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_6.setFont(font)
        self.TITULO_6.setText("")
        self.TITULO_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_6.setObjectName("TITULO_6")
        self.TITULO_7 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_7.setGeometry(QtCore.QRect(160, 340, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_7.setFont(font)
        self.TITULO_7.setText("")
        self.TITULO_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_7.setObjectName("TITULO_7")
        self.TITULO_8 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_8.setGeometry(QtCore.QRect(160, 370, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_8.setFont(font)
        self.TITULO_8.setText("")
        self.TITULO_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_8.setObjectName("TITULO_8")
        self.TITULO_9 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_9.setGeometry(QtCore.QRect(160, 400, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_9.setFont(font)
        self.TITULO_9.setText("")
        self.TITULO_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_9.setObjectName("TITULO_9")
        self.TITULO_10 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_10.setGeometry(QtCore.QRect(160, 430, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_10.setFont(font)
        self.TITULO_10.setText("")
        self.TITULO_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_10.setObjectName("TITULO_10")
        self.ATRAS = QtWidgets.QPushButton(self.centralwidget)
        self.ATRAS.setGeometry(QtCore.QRect(190, 10, 41, 31))
        self.ATRAS.setObjectName("ATRAS")
        self.PEDIDOSPENDIENTES = QtWidgets.QLabel(self.centralwidget)
        self.PEDIDOSPENDIENTES.setGeometry(QtCore.QRect(250, 10, 291, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.PEDIDOSPENDIENTES.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.PEDIDOSPENDIENTES.setFont(font)
        self.PEDIDOSPENDIENTES.setObjectName("PEDIDOSPENDIENTES")
        self.NUMPENDIENTES = QtWidgets.QLabel(self.centralwidget)
        self.NUMPENDIENTES.setGeometry(QtCore.QRect(550, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.NUMPENDIENTES.setFont(font)
        self.NUMPENDIENTES.setAlignment(QtCore.Qt.AlignCenter)
        self.NUMPENDIENTES.setObjectName("NUMPENDIENTES")
        self.AGREGARPEDIDO = QtWidgets.QPushButton(self.centralwidget)
        self.AGREGARPEDIDO.setGeometry(QtCore.QRect(40, 470, 91, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(30, 205, 92))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 205, 92))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 205, 92))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.AGREGARPEDIDO.setPalette(palette)
        self.AGREGARPEDIDO.setObjectName("AGREGARPEDIDO")
        self.CREARCOTIZACION = QtWidgets.QPushButton(self.centralwidget)
        self.CREARCOTIZACION.setGeometry(QtCore.QRect(140, 470, 91, 51))
        self.CREARCOTIZACION.setObjectName("CREARCOTIZACION")
        self.line_21 = QtWidgets.QFrame(self.centralwidget)
        self.line_21.setGeometry(QtCore.QRect(0, 40, 841, 21))
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.boton_noejecutado = QtWidgets.QPushButton(self.centralwidget)
        self.boton_noejecutado.setGeometry(QtCore.QRect(250, 60, 75, 41))
        self.boton_noejecutado.setObjectName("boton_noejecutado")
        self.boton_ejecutado = QtWidgets.QPushButton(self.centralwidget)
        self.boton_ejecutado.setGeometry(QtCore.QRect(350, 60, 75, 41))
        self.boton_ejecutado.setObjectName("boton_ejecutado")
        self.boton_ejcutadoyfirmado = QtWidgets.QPushButton(self.centralwidget)
        self.boton_ejcutadoyfirmado.setGeometry(QtCore.QRect(450, 60, 75, 41))
        self.boton_ejcutadoyfirmado.setObjectName("boton_ejcutadoyfirmado")
        self.boton_procesodepago = QtWidgets.QPushButton(self.centralwidget)
        self.boton_procesodepago.setGeometry(QtCore.QRect(550, 60, 75, 41))
        self.boton_procesodepago.setObjectName("boton_procesodepago")
        self.boton_cancelado = QtWidgets.QPushButton(self.centralwidget)
        self.boton_cancelado.setGeometry(QtCore.QRect(750, 60, 75, 41))
        self.boton_cancelado.setObjectName("boton_cancelado")
        self.PEDIDOSPENDIENTES_2 = QtWidgets.QLabel(self.centralwidget)
        self.PEDIDOSPENDIENTES_2.setGeometry(QtCore.QRect(10, 60, 111, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.PEDIDOSPENDIENTES_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.PEDIDOSPENDIENTES_2.setFont(font)
        self.PEDIDOSPENDIENTES_2.setObjectName("PEDIDOSPENDIENTES_2")
        self.line_22 = QtWidgets.QFrame(self.centralwidget)
        self.line_22.setGeometry(QtCore.QRect(0, 100, 841, 21))
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.boton_cancelado_2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_cancelado_2.setGeometry(QtCore.QRect(650, 60, 75, 41))
        self.boton_cancelado_2.setObjectName("boton_cancelado_2")
        self.boton_pendientes = QtWidgets.QPushButton(self.centralwidget)
        self.boton_pendientes.setGeometry(QtCore.QRect(150, 60, 75, 41))
        self.boton_pendientes.setObjectName("boton_pendientes")
        Gestor_Pedidos.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Gestor_Pedidos)
        self.statusbar.setObjectName("statusbar")
        Gestor_Pedidos.setStatusBar(self.statusbar)

        self.retranslateUi(Gestor_Pedidos)
        QtCore.QMetaObject.connectSlotsByName(Gestor_Pedidos)
        Gestor_Pedidos.setTabOrder(self.toolButton, self.toolButton_2)
        Gestor_Pedidos.setTabOrder(self.toolButton_2, self.toolButton_3)
        Gestor_Pedidos.setTabOrder(self.toolButton_3, self.toolButton_4)
        Gestor_Pedidos.setTabOrder(self.toolButton_4, self.toolButton_5)
        Gestor_Pedidos.setTabOrder(self.toolButton_5, self.toolButton_6)
        Gestor_Pedidos.setTabOrder(self.toolButton_6, self.toolButton_7)
        Gestor_Pedidos.setTabOrder(self.toolButton_7, self.toolButton_8)
        Gestor_Pedidos.setTabOrder(self.toolButton_8, self.toolButton_9)
        Gestor_Pedidos.setTabOrder(self.toolButton_9, self.toolButton_10)
        Gestor_Pedidos.setTabOrder(self.toolButton_10, self.ADELANTE)

    def retranslateUi(self, Gestor_Pedidos):
        _translate = QtCore.QCoreApplication.translate
        Gestor_Pedidos.setWindowTitle(_translate("Gestor_Pedidos", "MainWindow"))
        self.toolButton.setText(_translate("Gestor_Pedidos", "1"))
        self.toolButton_2.setText(_translate("Gestor_Pedidos", "2"))
        self.toolButton_3.setText(_translate("Gestor_Pedidos", "3"))
        self.toolButton_4.setText(_translate("Gestor_Pedidos", "4"))
        self.toolButton_5.setText(_translate("Gestor_Pedidos", "5"))
        self.toolButton_6.setText(_translate("Gestor_Pedidos", "6"))
        self.toolButton_7.setText(_translate("Gestor_Pedidos", "7"))
        self.toolButton_8.setText(_translate("Gestor_Pedidos", "8"))
        self.toolButton_9.setText(_translate("Gestor_Pedidos", "9"))
        self.toolButton_10.setText(_translate("Gestor_Pedidos", "10"))
        self.label.setText(_translate("Gestor_Pedidos", " PEDIDO "))
        self.label_2.setText(_translate("Gestor_Pedidos", "TIENDA"))
        self.label_3.setText(_translate("Gestor_Pedidos", "TITULO COTIZACION"))
        self.label_4.setText(_translate("Gestor_Pedidos", "# DE COTIZACION"))
        self.label_5.setText(_translate("Gestor_Pedidos", "ESTATUS"))
        self.label_6.setText(_translate("Gestor_Pedidos", "TIPO"))
        self.label_7.setText(_translate("Gestor_Pedidos", "INICIO EMBARQUE"))
        self.label_8.setText(_translate("Gestor_Pedidos", "FIN EMBARQUE"))
        self.ADELANTE.setText(_translate("Gestor_Pedidos", ">>>"))
        self.ATRAS.setText(_translate("Gestor_Pedidos", "<<<"))
        self.PEDIDOSPENDIENTES.setText(_translate("Gestor_Pedidos", "PEDIDOS PENDIENTES ------>"))
        self.NUMPENDIENTES.setText(_translate("Gestor_Pedidos", "999"))
        self.AGREGARPEDIDO.setText(_translate("Gestor_Pedidos", "Agregar Pedido"))
        self.CREARCOTIZACION.setText(_translate("Gestor_Pedidos", "Crear Cotizacion"))
        self.boton_noejecutado.setText(_translate("Gestor_Pedidos", "NO ejecutado"))
        self.boton_ejecutado.setText(_translate("Gestor_Pedidos", "Ejecutado"))
        self.boton_ejcutadoyfirmado.setText(_translate("Gestor_Pedidos", "Ejecutado \n"
"y Firmado"))
        self.boton_procesodepago.setText(_translate("Gestor_Pedidos", "Proceso\n"
"de pago"))
        self.boton_cancelado.setText(_translate("Gestor_Pedidos", "Cancelado"))
        self.PEDIDOSPENDIENTES_2.setText(_translate("Gestor_Pedidos", "FILTROS ->"))
        self.boton_cancelado_2.setText(_translate("Gestor_Pedidos", "Pagados"))
        self.boton_pendientes.setText(_translate("Gestor_Pedidos", "PENDIENTES"))
# botones de pruebas
        self.ADELANTE.clicked.connect(self.adelante)
        self.ATRAS.clicked.connect(self.atras)
        self.AGREGARPEDIDO.clicked.connect(self.ALTAPEDIDOS)
        self.boton_noejecutado.clicked.connect(self.filtronoejecutado)
        self.boton_ejecutado.clicked.connect(self.filtroejecutado)
        self.boton_ejcutadoyfirmado.clicked.connect(self.filtroejcutadoyfirmado)
        self.boton_procesodepago.clicked.connect(self.filtroprocesodepago)
        self.boton_cancelado.clicked.connect(self.filtrocancelado)
        self.boton_cancelado_2.clicked.connect(self.filtropagado)#boton de pagados
        self.boton_pendientes.clicked.connect(self.llenado) #boton de pendientes
        self.CREARCOTIZACION.clicked.connect(self.nuevacotizacion)
        self.toolButton.clicked.connect(self.boton1)
        self.toolButton_2.clicked.connect(self.boton2)
        self.toolButton_3.clicked.connect(self.boton3)
        self.toolButton_4.clicked.connect(self.boton4)
        self.toolButton_5.clicked.connect(self.boton5)
        self.toolButton_6.clicked.connect(self.boton6)
        self.toolButton_7.clicked.connect(self.boton7)
        self.toolButton_8.clicked.connect(self.boton8)
        self.toolButton_9.clicked.connect(self.boton9)
        self.toolButton_10.clicked.connect(self.boton10)
        # botones de prueba10

    def boton1(self):
        a=int(self.toolButton.text())
        vector=globals()['vectorglobal'][a]
        print(vector)
        prefijo=vector[8]
        pedido=str(vector[0])
        self.pasarinformacion(pedido,prefijo)
        self.Detallepedidos()
        return()
    def boton2(self):
        a=int(self.toolButton_2.text())
        vector=globals()['vectorglobal'][a]
        print(vector)
        prefijo=vector[8]
        pedido=str(vector[0])
        self.pasarinformacion(pedido,prefijo)
        self.Detallepedidos()
        return()
    def boton3(self):
        a = int(self.toolButton_3.text())
        vector = globals()['vectorglobal'][a]
        print(vector)
        prefijo = vector[8]
        pedido = str(vector[0])
        self.pasarinformacion(pedido, prefijo)
        self.Detallepedidos()
        return ()
    def boton4(self):
        a = int(self.toolButton_4.text())
        vector = globals()['vectorglobal'][a]
        print(vector)
        prefijo = vector[8]
        pedido = str(vector[0])
        self.pasarinformacion(pedido, prefijo)
        self.Detallepedidos()
        return ()
    def boton5(self):
        a = int(self.toolButton_5.text())
        vector = globals()['vectorglobal'][a]
        print(vector)
        prefijo = vector[8]
        pedido = str(vector[0])
        self.pasarinformacion(pedido, prefijo)
        self.Detallepedidos()
        return ()
    def boton6(self):
        a = int(self.toolButton_6.text())
        vector = globals()['vectorglobal'][a]
        print(vector)
        prefijo = vector[8]
        pedido = str(vector[0])
        self.pasarinformacion(pedido, prefijo)
        self.Detallepedidos()
        return ()
    def boton7(self):
        a = int(self.toolButton_7.text())
        vector = globals()['vectorglobal'][a]
        print(vector)
        prefijo = vector[8]
        pedido = str(vector[0])
        self.pasarinformacion(pedido, prefijo)
        self.Detallepedidos()
        return ()
    def boton8(self):
        a = int(self.toolButton_8.text())
        vector = globals()['vectorglobal'][a]
        print(vector)
        prefijo = vector[8]
        pedido = str(vector[0])
        self.pasarinformacion(pedido, prefijo)
        self.Detallepedidos()
        return ()
    def boton9(self):
        a = int(self.toolButton_9.text())
        vector = globals()['vectorglobal'][a]
        print(vector)
        prefijo = vector[8]
        pedido = str(vector[0])
        self.pasarinformacion(pedido, prefijo)
        self.Detallepedidos()
        return ()
    def boton10(self):
        a = int(self.toolButton_10.text())
        vector = globals()['vectorglobal'][a]
        print(vector)
        prefijo = vector[8]
        pedido = str(vector[0])
        self.pasarinformacion(pedido, prefijo)
        self.Detallepedidos()
        return ()

    def pasarinformacion(self,pedido,prefijo):

            print("pasarinfo")
            item = pedido
            cantidad = prefijo
            direccionBD = "items.db"
            try:
                sqliteConnection = sqlite3.connect(direccionBD)
                cursor = sqliteConnection.cursor()
                UPDATE = """Update pasar set item = ?, cantidad=?
                        where ID = 1
                        """
                data = (item, cantidad)
                cursor.execute(UPDATE, (data))
                sqliteConnection.commit()
                print("GUARDADO")
                cursor.close
            except sqlite3.Error as error:
                print("Error, ALV -----> ", error)
            finally:
                if (sqliteConnection):
                    sqliteConnection.close()
                    print("Cerrando conexión de Base de Datos")
            return ()

    def filtronoejecutado(self):
        vector = consultarfiltro_noejecutado()
        globals()["vectorglobal"] = vector
        self.llenargui(vector)
        self.PEDIDOSPENDIENTES.setText(str("Pedidos (NO EJECUTADOS)-->"))
        self.NUMPENDIENTES.setText(str(len(vector)))
        return()
    def filtroejecutado(self):
        vector = consultarfiltro_ejecutado()
        globals()["vectorglobal"] = vector
        self.llenargui(vector)
        self.PEDIDOSPENDIENTES.setText(str("Pedidos (EJECUTADOS)---->"))
        self.NUMPENDIENTES.setText(str(len(vector)))
        return()
    def filtroejcutadoyfirmado(self):
        vector = consultarfiltro_ejcutadoyfirmado()
        globals()["vectorglobal"] = vector
        self.llenargui(vector)
        self.PEDIDOSPENDIENTES.setText(str("Pedidos (Ejec y Firmado)--->"))
        self.NUMPENDIENTES.setText(str(len(vector)))
        return()
    def filtroprocesodepago(self):
        vector = consultarfiltro_procesodepago()
        globals()["vectorglobal"] = vector
        self.llenargui(vector)
        self.PEDIDOSPENDIENTES.setText(str("Pedidos (Proceso. Pago)---->"))
        self.NUMPENDIENTES.setText(str(len(vector)))
        return()
    def filtropagado(self):
        vector = consultarfiltro_pagado()
        globals()["vectorglobal"] = vector
        self.llenargui(vector)
        self.PEDIDOSPENDIENTES.setText(str("Pedidos (PAGADOS) ------->"))
        self.NUMPENDIENTES.setText(str(len(vector)))
        return()
    def filtrocancelado(self):
        vector = consultarfiltro_cancelados()
        globals()["vectorglobal"] = vector
        self.llenargui(vector)
        self.PEDIDOSPENDIENTES.setText(str("Pedidos (CANCELADOS)----->"))
        self.NUMPENDIENTES.setText(str(len(vector)))
        return()
    def Detallepedidos(self):
        script = "Detalle_pedido_3.py"
        # os.system(script)
        subprocess.Popen([sys.executable, script], stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT)
        sys.exit()
        return ()

    # funcion para consultar con filtro
    def alta(self):
        script = "ALTAPEDIDOS_3.py"
        # os.system(script)
        subprocess.Popen([sys.executable, script], stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT)
        sys.exit()
        return ()

    # llenado de informacion en ventana
    def llenado(self):
        # vector=consultartodo(2)
        vector = consultarfiltro()
        globals()["vectorglobal"] = vector
        self.llenargui(vector)
        self.PEDIDOSPENDIENTES.setText(str("PEDIDOS PENDIENTES ------>"))
        self.NUMPENDIENTES.setText(str(len(vector)))
        return ()

    # mover hacia ADELANTE
    def adelante(self):
        s = globals()["pagina"]
        pag = int(s + 10)

        globals()["pagina"] = pag
        vector = globals()["vectorglobal"]
        self.llenargui(vector)

    # mover hacia ATRAS
    def atras(self):
        s = globals()["pagina"]
        if s < 9:
            print("no puedo retroceder más")
            return ()
        else:
            pag = int(s - 10)
            globals()["pagina"] = pag
            vector = globals()["vectorglobal"]
            self.llenargui(vector)

    def llenargui(self, info):
        self.limpiar()
        vector = info
        pag = globals()["pagina"]
        globals()["vectorglobal"] = vector
        longitudvector = len(vector)
        # print("tamaño vector-> ",longitudvector)

        # posición del vector
        a1 = 0
        a2 = 1
        a3 = 2
        a4 = 3
        a5 = 4
        a6 = 5
        a7 = 6
        a8 = 7
        # posición de la pagina
        com1 = int(pag)
        com2 = int(pag + 1)
        com3 = int(pag + 2)
        com4 = int(pag + 3)
        com5 = int(pag + 4)
        com6 = int(pag + 5)
        com7 = int(pag + 6)
        com8 = int(pag + 7)
        com9 = int(pag + 8)
        com10 = int(pag + 9)

        if longitudvector == 0:
            print("no hay consultas")
            return ()
        if longitudvector > com1:
            pos = pag
            self.toolButton.setText(str(pos))
            self.toolButton.setEnabled(1)
            self.PED_1.setText(str(vector[pos][a1]))
            self.TIENDA_1.setText(str(vector[pos][a2]))
            self.TITULO_1.setText(vector[pos][a3])
            self.COT_1.setText(vector[pos][a4])
            self.STATS_1.setText(traduccionestatus(str(vector[pos][a5])))
            self.DOCS_1.setText(traducciontipo(str(vector[pos][a6])))
            self.IEMBARQUE_1.setText(convertirFECHA(str(vector[pos][a7])))
            self.ENTREGA_1.setText(convertirFECHA(str(vector[pos][a8])))

        if longitudvector > com2:
            pos = pag + 1
            self.toolButton_2.setText(str(pos))
            self.toolButton_2.setEnabled(1)
            self.PED_2.setText(str(vector[pos][a1]))
            self.TIENDA_2.setText(str(vector[pos][a2]))
            self.TITULO_2.setText(vector[pos][a3])
            self.COT_2.setText(vector[pos][a4])
            self.STATS_2.setText(traduccionestatus(str(vector[pos][a5])))
            self.DOCS_2.setText(traducciontipo(str(vector[pos][a6])))
            self.IEMBARQUE_2.setText(convertirFECHA(str(vector[pos][a7])))
            self.ENTREGA_2.setText(convertirFECHA(str(vector[pos][a8])))

        if longitudvector > com3:
            pos = pag + 2
            self.toolButton_3.setText(str(pos))
            self.toolButton_3.setEnabled(1)
            self.PED_3.setText(str(vector[pos][a1]))
            self.TIENDA_3.setText(str(vector[pos][a2]))
            self.TITULO_3.setText(vector[pos][a3])
            self.COT_3.setText(vector[pos][a4])
            self.STATS_3.setText(traduccionestatus(str(vector[pos][a5])))
            self.DOCS_3.setText(traducciontipo(str(vector[pos][a6])))
            self.IEMBARQUE_3.setText(convertirFECHA(str(vector[pos][a7])))
            self.ENTREGA_3.setText(convertirFECHA(str(vector[pos][a8])))
        if longitudvector > com4:
            pos = pag + 3
            self.toolButton_4.setText(str(pos))
            self.toolButton_4.setEnabled(1)
            self.PED_4.setText(str(vector[pos][a1]))
            self.TIENDA_4.setText(str(vector[pos][a2]))
            self.TITULO_4.setText(vector[pos][a3])
            self.COT_4.setText(vector[pos][a4])
            self.STATS_4.setText(traduccionestatus(str(vector[pos][a5])))
            self.DOCS_4.setText(traducciontipo(str(vector[pos][a6])))
            self.IEMBARQUE_4.setText(convertirFECHA(str(vector[pos][a7])))
            self.ENTREGA_4.setText(convertirFECHA(str(vector[pos][a8])))
        if longitudvector > com5:
            pos = pag + 4
            self.toolButton_5.setText(str(pos))
            self.toolButton_5.setEnabled(1)
            self.PED_5.setText(str(vector[pos][a1]))
            self.TIENDA_5.setText(str(vector[pos][a2]))
            self.TITULO_5.setText(vector[pos][a3])
            self.COT_5.setText(vector[pos][a4])
            self.STATS_5.setText(traduccionestatus(str(vector[pos][a5])))
            self.DOCS_5.setText(traducciontipo(str(vector[pos][a6])))
            self.IEMBARQUE_5.setText(convertirFECHA(str(vector[pos][a7])))
            self.ENTREGA_5.setText(convertirFECHA(str(vector[pos][a8])))
        if longitudvector > com6:
            pos = pag + 5
            self.toolButton_6.setText(str(pos))
            self.toolButton_6.setEnabled(1)
            self.PED_6.setText(str(vector[pos][a1]))
            self.TIENDA_6.setText(str(vector[pos][a2]))
            self.TITULO_6.setText(vector[pos][a3])
            self.COT_6.setText(vector[pos][a4])
            self.STATS_6.setText(traduccionestatus(str(vector[pos][a5])))
            self.DOCS_6.setText(traducciontipo(str(vector[pos][a6])))
            self.IEMBARQUE_6.setText(convertirFECHA(str(vector[pos][a7])))
            self.ENTREGA_6.setText(convertirFECHA(str(vector[pos][a8])))
        if longitudvector > com7:
            pos = pag + 6
            self.toolButton_7.setText(str(pos))
            self.toolButton_7.setEnabled(1)
            self.PED_7.setText(str(vector[pos][a1]))
            self.TIENDA_7.setText(str(vector[pos][a2]))
            self.TITULO_7.setText(vector[pos][a3])
            self.COT_7.setText(vector[pos][a4])
            self.STATS_7.setText(traduccionestatus(str(vector[pos][a5])))
            self.DOCS_7.setText(traducciontipo(str(vector[pos][a6])))
            self.IEMBARQUE_7.setText(convertirFECHA(str(vector[pos][a7])))
            self.ENTREGA_7.setText(convertirFECHA(str(vector[pos][a8])))
        if longitudvector > com8:
            pos = pag + 7
            self.toolButton_8.setText(str(pos))
            self.toolButton_8.setEnabled(1)
            self.PED_8.setText(str(vector[pos][a1]))
            self.TIENDA_8.setText(str(vector[pos][a2]))
            self.TITULO_8.setText(vector[pos][a3])
            self.COT_8.setText(vector[pos][a4])
            self.STATS_8.setText(traduccionestatus(str(vector[pos][a5])))
            self.DOCS_8.setText(traducciontipo(str(vector[pos][a6])))
            self.IEMBARQUE_8.setText(convertirFECHA(str(vector[pos][a7])))
            self.ENTREGA_8.setText(convertirFECHA(str(vector[pos][a8])))
        if longitudvector > com9:
            pos = pag + 8
            self.toolButton_9.setText(str(pos))
            self.toolButton_9.setEnabled(1)
            self.PED_9.setText(str(vector[pos][a1]))
            self.TIENDA_9.setText(str(vector[pos][a2]))
            self.TITULO_9.setText(vector[pos][a3])
            self.COT_9.setText(vector[pos][a4])
            self.STATS_9.setText(traduccionestatus(str(vector[pos][a5])))
            self.DOCS_9.setText(traducciontipo(str(vector[pos][a6])))
            self.IEMBARQUE_9.setText(convertirFECHA(str(vector[pos][a7])))
            self.ENTREGA_9.setText(convertirFECHA(str(vector[pos][a8])))
        if longitudvector > com10:
            pos = pag + 9
            self.toolButton_10.setText(str(pos))
            self.toolButton_10.setEnabled(1)
            self.PED_10.setText(str(vector[pos][a1]))
            self.TIENDA_10.setText(str(vector[pos][a2]))
            self.TITULO_10.setText(vector[pos][a3])
            self.COT_10.setText(vector[pos][a4])
            self.STATS_10.setText(traduccionestatus(str(vector[pos][a5])))
            self.DOCS_10.setText(traducciontipo(str(vector[pos][a6])))
            self.IEMBARQUE_10.setText(convertirFECHA(str(vector[pos][a7])))
            self.ENTREGA_10.setText(convertirFECHA(str(vector[pos][a8])))

        return ()

    def limpiar(self):
        act = 0

        self.toolButton.setText("...")
        self.toolButton.setEnabled(act)
        self.PED_1.setText("")
        self.TIENDA_1.setText("")
        self.TITULO_1.setText("")
        self.COT_1.setText("")
        self.STATS_1.setText("")
        self.DOCS_1.setText("")
        self.IEMBARQUE_1.setText("")
        self.ENTREGA_1.setText("")

        self.toolButton_2.setText("...")
        self.toolButton_2.setEnabled(act)
        self.PED_2.setText("")
        self.TIENDA_2.setText("")
        self.TITULO_2.setText("")
        self.COT_2.setText("")
        self.STATS_2.setText("")
        self.DOCS_2.setText("")
        self.IEMBARQUE_2.setText("")
        self.ENTREGA_2.setText("")

        self.toolButton_3.setText("...")
        self.toolButton_3.setEnabled(act)
        self.PED_3.setText("")
        self.TIENDA_3.setText("")
        self.TITULO_3.setText("")
        self.COT_3.setText("")
        self.STATS_3.setText("")
        self.DOCS_3.setText("")
        self.IEMBARQUE_3.setText("")
        self.ENTREGA_3.setText("")

        self.toolButton_4.setText("...")
        self.toolButton_4.setEnabled(act)
        self.PED_4.setText("")
        self.TIENDA_4.setText("")
        self.TITULO_4.setText("")
        self.COT_4.setText("")
        self.STATS_4.setText("")
        self.DOCS_4.setText("")
        self.IEMBARQUE_4.setText("")
        self.ENTREGA_4.setText("")

        self.toolButton_5.setText("...")
        self.toolButton_5.setEnabled(act)
        self.PED_5.setText("")
        self.TIENDA_5.setText("")
        self.TITULO_5.setText("")
        self.COT_5.setText("")
        self.STATS_5.setText("")
        self.DOCS_5.setText("")
        self.IEMBARQUE_5.setText("")
        self.ENTREGA_5.setText("")

        self.toolButton_6.setText("...")
        self.toolButton_6.setEnabled(act)
        self.PED_6.setText("")
        self.TIENDA_6.setText("")
        self.TITULO_6.setText("")
        self.COT_6.setText("")
        self.STATS_6.setText("")
        self.DOCS_6.setText("")
        self.IEMBARQUE_6.setText("")
        self.ENTREGA_6.setText("")

        self.toolButton_7.setText("...")
        self.toolButton_7.setEnabled(act)
        self.PED_7.setText("")
        self.TIENDA_7.setText("")
        self.TITULO_7.setText("")
        self.COT_7.setText("")
        self.STATS_7.setText("")
        self.DOCS_7.setText("")
        self.IEMBARQUE_7.setText("")
        self.ENTREGA_7.setText("")

        self.toolButton_8.setText("...")
        self.toolButton_8.setEnabled(act)
        self.PED_8.setText("")
        self.TIENDA_8.setText("")
        self.TITULO_8.setText("")
        self.COT_8.setText("")
        self.STATS_8.setText("")
        self.DOCS_8.setText("")
        self.IEMBARQUE_8.setText("")
        self.ENTREGA_8.setText("")

        self.toolButton_9.setText("...")
        self.toolButton_9.setEnabled(act)
        self.PED_9.setText("")
        self.TIENDA_9.setText("")
        self.TITULO_9.setText("")
        self.COT_9.setText("")
        self.STATS_9.setText("")
        self.DOCS_9.setText("")
        self.IEMBARQUE_9.setText("")
        self.ENTREGA_9.setText("")

        self.toolButton_10.setText("...")
        self.toolButton_10.setEnabled(act)
        self.PED_10.setText("")
        self.TIENDA_10.setText("")
        self.TITULO_10.setText("")
        self.COT_10.setText("")
        self.STATS_10.setText("")
        self.DOCS_10.setText("")
        self.IEMBARQUE_10.setText("")
        self.ENTREGA_10.setText("")
        return ()


def convertirFECHA(tiempo):
    fecha = time.strftime("%D ", time.localtime(int(tiempo)))
    return (fecha)

# self.toolButton.text() #obtienes valor del texto del botóntool
# self.toolButton.setText("xxx") #cambiar el texto del botóntool
# self.toolButton.setEnabled(0) #activar o desactivar botontool con 1 ó 0
def consultartodo(determinante):
    print("++++++++BUSCANDO++++++++")
    try:
        sqliteConnection = sqlite3.connect(basedatos)
        cursor = sqliteConnection.cursor()
        print("Successfully Connected to SQLite")
        SELECT = """SELECT * from pedidos  """  # where id = ?  """
        cursor.execute(SELECT)  # ,(determinante,))
        # record=cursor.fetchone()
        record = cursor.fetchall()

        print("Record Updated successfully")
        cursor.close

    except sqlite3.Error as error:
        print("Error, ALV -----> ", error)
    finally:
        if (sqliteConnection):
            sqliteConnection.close()
            print("Cerrando conexión de Base de Datos")
    return (record)


def consultarfiltro():
    print("FILTRANDO")
    try:
        sqliteConnection = sqlite3.connect(basedatos)
        cursor = sqliteConnection.cursor()
        # print("Successfully Connected to SQLite")
        SELECT = """SELECT 
                numpedido, numtienda, titulocotizacion,
                numcotizacion, estatus, tipo,
                timestampIembarque, timestampFembarque,
                prefijo

                FROM
                pedidos


                WHERE
                estatus < 4 

                ORDER BY
                timestampIembarque ASC                
                """
        cursor.execute(SELECT)
        record = cursor.fetchall()
        cursor.close

    except sqlite3.Error as error:
        print("Error, ALV -----> ", error)
    finally:
        if (sqliteConnection):
            sqliteConnection.close()
            # print("Cerrando conexión de Base de Datos")
    return (record)

def consultarfiltro_noejecutado():
    print("FILTRANDO")
    try:
        sqliteConnection = sqlite3.connect(basedatos)
        cursor = sqliteConnection.cursor()
        # print("Successfully Connected to SQLite")
        SELECT = """SELECT 
                numpedido, numtienda, titulocotizacion,
                numcotizacion, estatus, tipo,
                timestampIembarque, timestampFembarque,
                prefijo

                FROM
                pedidos


                WHERE
                estatus = 0 

                ORDER BY
                timestampIembarque ASC                
                """
        cursor.execute(SELECT)
        record = cursor.fetchall()
        cursor.close

    except sqlite3.Error as error:
        print("Error, ALV -----> ", error)
    finally:
        if (sqliteConnection):
            sqliteConnection.close()
            globals()["vectorglobal"] = []
            # print("Cerrando conexión de Base de Datos")
    return (record)

def consultarfiltro_ejecutado():
    print("FILTRANDO")
    try:
        sqliteConnection = sqlite3.connect(basedatos)
        cursor = sqliteConnection.cursor()
        # print("Successfully Connected to SQLite")
        SELECT = """SELECT 
                numpedido, numtienda, titulocotizacion,
                numcotizacion, estatus, tipo,
                timestampIembarque, timestampFembarque,
                prefijo

                FROM
                pedidos


                WHERE
                estatus = 1

                ORDER BY
                timestampIembarque ASC                
                """
        cursor.execute(SELECT)
        record = cursor.fetchall()
        cursor.close

    except sqlite3.Error as error:
        print("Error, ALV -----> ", error)
    finally:
        if (sqliteConnection):
            sqliteConnection.close()
            globals()["vectorglobal"] = []
            # print("Cerrando conexión de Base de Datos")
    return (record)

def consultarfiltro_ejcutadoyfirmado():
    print("FILTRANDO")
    try:
        sqliteConnection = sqlite3.connect(basedatos)
        cursor = sqliteConnection.cursor()
        # print("Successfully Connected to SQLite")
        SELECT = """SELECT 
                numpedido, numtienda, titulocotizacion,
                numcotizacion, estatus, tipo,
                timestampIembarque, timestampFembarque,
                prefijo

                FROM
                pedidos


                WHERE
                estatus = 2

                ORDER BY
                timestampIembarque ASC                
                """
        cursor.execute(SELECT)
        record = cursor.fetchall()
        cursor.close
    except sqlite3.Error as error:
        print("Error, ALV -----> ", error)
    finally:
        if (sqliteConnection):
            sqliteConnection.close()
            globals()["vectorglobal"] = []
            # print("Cerrando conexión de Base de Datos")
    return (record)
#consultarfiltro_procesodepago
def consultarfiltro_procesodepago():
    print("FILTRANDO")
    try:
        sqliteConnection = sqlite3.connect(basedatos)
        cursor = sqliteConnection.cursor()
        # print("Successfully Connected to SQLite")
        SELECT = """SELECT 
                numpedido, numtienda, titulocotizacion,
                numcotizacion, estatus, tipo,
                timestampIembarque, timestampFembarque,
                prefijo

                FROM
                pedidos


                WHERE
                estatus = 3

                ORDER BY
                timestampIembarque ASC                
                """
        cursor.execute(SELECT)
        record = cursor.fetchall()
        cursor.close
    except sqlite3.Error as error:
        print("Error, ALV -----> ", error)
    finally:
        if (sqliteConnection):
            sqliteConnection.close()
            globals()["vectorglobal"] = []
            # print("Cerrando conexión de Base de Datos")
    return (record)
#consultarfiltro_pagado
def consultarfiltro_pagado():
    print("FILTRANDO")
    try:
        sqliteConnection = sqlite3.connect(basedatos)
        cursor = sqliteConnection.cursor()
        # print("Successfully Connected to SQLite")
        SELECT = """SELECT 
                numpedido, numtienda, titulocotizacion,
                numcotizacion, estatus, tipo,
                timestampIembarque, timestampFembarque,
                prefijo

                FROM
                pedidos


                WHERE
                estatus = 4

                ORDER BY
                timestampIembarque ASC                
                """
        cursor.execute(SELECT)
        record = cursor.fetchall()
        cursor.close
    except sqlite3.Error as error:
        print("Error, ALV -----> ", error)
    finally:
        if (sqliteConnection):
            sqliteConnection.close()
            globals()["vectorglobal"] = []
            # print("Cerrando conexión de Base de Datos")
    return (record)
#consultarfiltro_cancelados
def consultarfiltro_cancelados():
    print("FILTRANDO")
    try:
        sqliteConnection = sqlite3.connect(basedatos)
        cursor = sqliteConnection.cursor()
        # print("Successfully Connected to SQLite")
        SELECT = """SELECT 
                numpedido, numtienda, titulocotizacion,
                numcotizacion, estatus, tipo,
                timestampIembarque, timestampFembarque,
                prefijo

                FROM
                pedidos


                WHERE
                estatus = 5

                ORDER BY
                timestampIembarque ASC                
                """
        cursor.execute(SELECT)
        record = cursor.fetchall()
        cursor.close
    except sqlite3.Error as error:
        print("Error, ALV -----> ", error)
    finally:
        if (sqliteConnection):
            sqliteConnection.close()
            globals()["vectorglobal"] = []
            # print("Cerrando conexión de Base de Datos")
    return (record)


def traduccionestatus(statusID):
    status = int(statusID)
    if status == 0:
        return ("NO ejecutado")
    if status == 1:
        return ("Ejecutado")
    if status == 2:
        return ("Ejec. y firmado")
    if status == 3:
        return ("Proceso Pago")
    if status == 4:
        return ("Pagado")
    if status == 5:
        return ("Cancelado")

def traducciontipo(tipoID):
    tipo = int(tipoID)
    if tipo == 1:
        return ("iguala")
    if tipo == 0:
        return ("correctivo")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Gestor_Pedidos = QtWidgets.QMainWindow()
    ui = Ui_Gestor_Pedidos()
    ui.setupUi(Gestor_Pedidos)
    Gestor_Pedidos.show()
    print("ejecutando funciones")
    ui.llenado()
    sys.exit(app.exec_())

