from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import date, datetime
from visor_cotizacion_1 import Ui_Dialog_visor_cotizador
from COTIZADOR_1_2_1 import *#Ui_MainWindow_cotizador
import logging
import sqlite3
import json
import os
import subprocess
import time
import sys


#VARIABLES GLOBALES
vectorglobal=[]
pagina=0
#VARIABLES GLOBALES
class Ui_Gestor_Cot(object):
    def abrircotizador(self): #NO USAR
        script = "COTIZADOR_1_2_1.py"
        subprocess.Popen([sys.executable, script], stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT)
        sys.exit()
        return ()

    def abrirlistacotizacion(self):
        script = "abrircotizacion.py"
        subprocess.Popen([sys.executable, script], stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT)
        sys.exit()
        return ()

    def setupUi_GESTORCOTIZACIONES(self, Gestor_Pedidos):
        Gestor_Pedidos.setObjectName("Gestor_Pedidos")
        Gestor_Pedidos.setEnabled(True)
        Gestor_Pedidos.resize(812, 475)
        Gestor_Pedidos.setMinimumSize(QtCore.QSize(812, 475))
        Gestor_Pedidos.setMaximumSize(QtCore.QSize(812, 475))
        Gestor_Pedidos.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(Gestor_Pedidos)
        self.centralwidget.setObjectName("centralwidget")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(10, 80, 25, 19))
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(10, 110, 25, 19))
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_3.setGeometry(QtCore.QRect(10, 140, 25, 19))
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_4.setGeometry(QtCore.QRect(10, 170, 25, 19))
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_5.setGeometry(QtCore.QRect(10, 200, 25, 19))
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_6 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_6.setGeometry(QtCore.QRect(10, 230, 25, 19))
        self.toolButton_6.setObjectName("toolButton_6")
        self.toolButton_7 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_7.setGeometry(QtCore.QRect(10, 260, 25, 19))
        self.toolButton_7.setObjectName("toolButton_7")
        self.toolButton_8 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_8.setGeometry(QtCore.QRect(10, 290, 25, 19))
        self.toolButton_8.setObjectName("toolButton_8")
        self.toolButton_9 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_9.setGeometry(QtCore.QRect(10, 320, 25, 19))
        self.toolButton_9.setObjectName("toolButton_9")
        self.toolButton_10 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_10.setGeometry(QtCore.QRect(10, 350, 25, 19))
        self.toolButton_10.setObjectName("toolButton_10")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 50, 161, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(340, 50, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(520, 50, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(720, 40, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(100, 60, 20, 321))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(300, 60, 20, 321))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(490, 60, 20, 321))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(590, 60, 20, 321))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(700, 60, 20, 321))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(30, 50, 20, 331))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.TIENDA_1 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_1.setGeometry(QtCore.QRect(50, 80, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_1.setFont(font)
        self.TIENDA_1.setText("")
        self.TIENDA_1.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_1.setObjectName("TIENDA_1")
        self.TIENDA_2 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_2.setGeometry(QtCore.QRect(50, 110, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_2.setFont(font)
        self.TIENDA_2.setText("")
        self.TIENDA_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_2.setObjectName("TIENDA_2")
        self.TIENDA_3 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_3.setGeometry(QtCore.QRect(50, 140, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_3.setFont(font)
        self.TIENDA_3.setText("")
        self.TIENDA_3.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_3.setObjectName("TIENDA_3")
        self.TIENDA_4 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_4.setGeometry(QtCore.QRect(50, 170, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_4.setFont(font)
        self.TIENDA_4.setText("")
        self.TIENDA_4.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_4.setObjectName("TIENDA_4")
        self.TIENDA_5 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_5.setGeometry(QtCore.QRect(50, 200, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_5.setFont(font)
        self.TIENDA_5.setText("")
        self.TIENDA_5.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_5.setObjectName("TIENDA_5")
        self.TIENDA_6 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_6.setGeometry(QtCore.QRect(50, 230, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_6.setFont(font)
        self.TIENDA_6.setText("")
        self.TIENDA_6.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_6.setObjectName("TIENDA_6")
        self.TIENDA_7 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_7.setGeometry(QtCore.QRect(50, 260, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_7.setFont(font)
        self.TIENDA_7.setText("")
        self.TIENDA_7.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_7.setObjectName("TIENDA_7")
        self.TIENDA_8 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_8.setGeometry(QtCore.QRect(50, 290, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_8.setFont(font)
        self.TIENDA_8.setText("")
        self.TIENDA_8.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_8.setObjectName("TIENDA_8")
        self.TIENDA_9 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_9.setGeometry(QtCore.QRect(50, 320, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_9.setFont(font)
        self.TIENDA_9.setText("")
        self.TIENDA_9.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_9.setObjectName("TIENDA_9")
        self.TIENDA_10 = QtWidgets.QLabel(self.centralwidget)
        self.TIENDA_10.setGeometry(QtCore.QRect(50, 350, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TIENDA_10.setFont(font)
        self.TIENDA_10.setText("")
        self.TIENDA_10.setAlignment(QtCore.Qt.AlignCenter)
        self.TIENDA_10.setObjectName("TIENDA_10")
        self.COT_1 = QtWidgets.QLabel(self.centralwidget)
        self.COT_1.setGeometry(QtCore.QRect(320, 80, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_1.setFont(font)
        self.COT_1.setText("")
        self.COT_1.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_1.setObjectName("COT_1")
        self.COT_2 = QtWidgets.QLabel(self.centralwidget)
        self.COT_2.setGeometry(QtCore.QRect(320, 110, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_2.setFont(font)
        self.COT_2.setText("")
        self.COT_2.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_2.setObjectName("COT_2")
        self.COT_3 = QtWidgets.QLabel(self.centralwidget)
        self.COT_3.setGeometry(QtCore.QRect(320, 140, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_3.setFont(font)
        self.COT_3.setText("")
        self.COT_3.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_3.setObjectName("COT_3")
        self.COT_4 = QtWidgets.QLabel(self.centralwidget)
        self.COT_4.setGeometry(QtCore.QRect(320, 170, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_4.setFont(font)
        self.COT_4.setText("")
        self.COT_4.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_4.setObjectName("COT_4")
        self.COT_5 = QtWidgets.QLabel(self.centralwidget)
        self.COT_5.setGeometry(QtCore.QRect(320, 200, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_5.setFont(font)
        self.COT_5.setText("")
        self.COT_5.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_5.setObjectName("COT_5")
        self.COT_6 = QtWidgets.QLabel(self.centralwidget)
        self.COT_6.setGeometry(QtCore.QRect(320, 230, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_6.setFont(font)
        self.COT_6.setText("")
        self.COT_6.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_6.setObjectName("COT_6")
        self.COT_7 = QtWidgets.QLabel(self.centralwidget)
        self.COT_7.setGeometry(QtCore.QRect(320, 260, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_7.setFont(font)
        self.COT_7.setText("")
        self.COT_7.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_7.setObjectName("COT_7")
        self.COT_8 = QtWidgets.QLabel(self.centralwidget)
        self.COT_8.setGeometry(QtCore.QRect(320, 290, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_8.setFont(font)
        self.COT_8.setText("")
        self.COT_8.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_8.setObjectName("COT_8")
        self.COT_9 = QtWidgets.QLabel(self.centralwidget)
        self.COT_9.setGeometry(QtCore.QRect(320, 320, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_9.setFont(font)
        self.COT_9.setText("")
        self.COT_9.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_9.setObjectName("COT_9")
        self.COT_10 = QtWidgets.QLabel(self.centralwidget)
        self.COT_10.setGeometry(QtCore.QRect(320, 350, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.COT_10.setFont(font)
        self.COT_10.setText("")
        self.COT_10.setAlignment(QtCore.Qt.AlignCenter)
        self.COT_10.setObjectName("COT_10")
        self.STATS_1 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_1.setGeometry(QtCore.QRect(500, 80, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_1.setFont(font)
        self.STATS_1.setText("")
        self.STATS_1.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_1.setObjectName("STATS_1")
        self.STATS_2 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_2.setGeometry(QtCore.QRect(500, 110, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_2.setFont(font)
        self.STATS_2.setText("")
        self.STATS_2.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_2.setObjectName("STATS_2")
        self.STATS_3 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_3.setGeometry(QtCore.QRect(500, 140, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_3.setFont(font)
        self.STATS_3.setText("")
        self.STATS_3.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_3.setObjectName("STATS_3")
        self.STATS_4 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_4.setGeometry(QtCore.QRect(500, 170, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_4.setFont(font)
        self.STATS_4.setText("")
        self.STATS_4.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_4.setObjectName("STATS_4")
        self.STATS_5 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_5.setGeometry(QtCore.QRect(500, 200, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_5.setFont(font)
        self.STATS_5.setText("")
        self.STATS_5.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_5.setObjectName("STATS_5")
        self.STATS_6 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_6.setGeometry(QtCore.QRect(500, 230, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_6.setFont(font)
        self.STATS_6.setText("")
        self.STATS_6.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_6.setObjectName("STATS_6")
        self.STATS_7 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_7.setGeometry(QtCore.QRect(500, 260, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_7.setFont(font)
        self.STATS_7.setText("")
        self.STATS_7.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_7.setObjectName("STATS_7")
        self.STATS_8 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_8.setGeometry(QtCore.QRect(500, 290, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_8.setFont(font)
        self.STATS_8.setText("")
        self.STATS_8.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_8.setObjectName("STATS_8")
        self.STATS_9 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_9.setGeometry(QtCore.QRect(500, 320, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_9.setFont(font)
        self.STATS_9.setText("")
        self.STATS_9.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_9.setObjectName("STATS_9")
        self.STATS_10 = QtWidgets.QLabel(self.centralwidget)
        self.STATS_10.setGeometry(QtCore.QRect(500, 350, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.STATS_10.setFont(font)
        self.STATS_10.setText("")
        self.STATS_10.setAlignment(QtCore.Qt.AlignCenter)
        self.STATS_10.setObjectName("STATS_10")
        self.FECHA_1 = QtWidgets.QLabel(self.centralwidget)
        self.FECHA_1.setGeometry(QtCore.QRect(720, 80, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.FECHA_1.setFont(font)
        self.FECHA_1.setText("")
        self.FECHA_1.setAlignment(QtCore.Qt.AlignCenter)
        self.FECHA_1.setObjectName("FECHA_1")
        self.FECHA_2 = QtWidgets.QLabel(self.centralwidget)
        self.FECHA_2.setGeometry(QtCore.QRect(720, 110, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.FECHA_2.setFont(font)
        self.FECHA_2.setText("")
        self.FECHA_2.setAlignment(QtCore.Qt.AlignCenter)
        self.FECHA_2.setObjectName("FECHA_2")
        self.FECHA_3 = QtWidgets.QLabel(self.centralwidget)
        self.FECHA_3.setGeometry(QtCore.QRect(720, 140, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.FECHA_3.setFont(font)
        self.FECHA_3.setText("")
        self.FECHA_3.setAlignment(QtCore.Qt.AlignCenter)
        self.FECHA_3.setObjectName("FECHA_3")
        self.FECHA_4 = QtWidgets.QLabel(self.centralwidget)
        self.FECHA_4.setGeometry(QtCore.QRect(720, 170, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.FECHA_4.setFont(font)
        self.FECHA_4.setText("")
        self.FECHA_4.setAlignment(QtCore.Qt.AlignCenter)
        self.FECHA_4.setObjectName("FECHA_4")
        self.FECHA_5 = QtWidgets.QLabel(self.centralwidget)
        self.FECHA_5.setGeometry(QtCore.QRect(720, 200, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.FECHA_5.setFont(font)
        self.FECHA_5.setText("")
        self.FECHA_5.setAlignment(QtCore.Qt.AlignCenter)
        self.FECHA_5.setObjectName("FECHA_5")
        self.FECHA_6 = QtWidgets.QLabel(self.centralwidget)
        self.FECHA_6.setGeometry(QtCore.QRect(720, 230, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.FECHA_6.setFont(font)
        self.FECHA_6.setText("")
        self.FECHA_6.setAlignment(QtCore.Qt.AlignCenter)
        self.FECHA_6.setObjectName("FECHA_6")
        self.FECHA_7 = QtWidgets.QLabel(self.centralwidget)
        self.FECHA_7.setGeometry(QtCore.QRect(720, 260, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.FECHA_7.setFont(font)
        self.FECHA_7.setText("")
        self.FECHA_7.setAlignment(QtCore.Qt.AlignCenter)
        self.FECHA_7.setObjectName("FECHA_7")
        self.FECHA_8 = QtWidgets.QLabel(self.centralwidget)
        self.FECHA_8.setGeometry(QtCore.QRect(720, 290, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.FECHA_8.setFont(font)
        self.FECHA_8.setText("")
        self.FECHA_8.setAlignment(QtCore.Qt.AlignCenter)
        self.FECHA_8.setObjectName("FECHA_8")
        self.FECHA_9 = QtWidgets.QLabel(self.centralwidget)
        self.FECHA_9.setGeometry(QtCore.QRect(720, 320, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.FECHA_9.setFont(font)
        self.FECHA_9.setText("")
        self.FECHA_9.setAlignment(QtCore.Qt.AlignCenter)
        self.FECHA_9.setObjectName("FECHA_9")
        self.FECHA_10 = QtWidgets.QLabel(self.centralwidget)
        self.FECHA_10.setGeometry(QtCore.QRect(720, 350, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.FECHA_10.setFont(font)
        self.FECHA_10.setText("")
        self.FECHA_10.setAlignment(QtCore.Qt.AlignCenter)
        self.FECHA_10.setObjectName("FECHA_10")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(40, 70, 781, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_8.setFont(font)
        self.line_8.setLineWidth(1)
        self.line_8.setMidLineWidth(1)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(40, 100, 781, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_9.setFont(font)
        self.line_9.setLineWidth(1)
        self.line_9.setMidLineWidth(1)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(40, 130, 781, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_10.setFont(font)
        self.line_10.setLineWidth(1)
        self.line_10.setMidLineWidth(1)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(40, 160, 781, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_11.setFont(font)
        self.line_11.setLineWidth(1)
        self.line_11.setMidLineWidth(1)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(40, 190, 781, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_12.setFont(font)
        self.line_12.setLineWidth(1)
        self.line_12.setMidLineWidth(1)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(40, 220, 781, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_13.setFont(font)
        self.line_13.setLineWidth(1)
        self.line_13.setMidLineWidth(1)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(40, 250, 781, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_14.setFont(font)
        self.line_14.setLineWidth(1)
        self.line_14.setMidLineWidth(1)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(40, 280, 781, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_15.setFont(font)
        self.line_15.setLineWidth(1)
        self.line_15.setMidLineWidth(1)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(40, 310, 781, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_16.setFont(font)
        self.line_16.setLineWidth(1)
        self.line_16.setMidLineWidth(1)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(40, 340, 781, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_17.setFont(font)
        self.line_17.setLineWidth(1)
        self.line_17.setMidLineWidth(1)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(40, 370, 781, 16))
        font = QtGui.QFont()
        font.setPointSize(3)
        self.line_19.setFont(font)
        self.line_19.setLineWidth(1)
        self.line_19.setMidLineWidth(1)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.ADELANTE = QtWidgets.QPushButton(self.centralwidget)
        self.ADELANTE.setGeometry(QtCore.QRect(620, 10, 41, 31))
        self.ADELANTE.setObjectName("ADELANTE")
        self.TITULO_1 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_1.setGeometry(QtCore.QRect(120, 80, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_1.setFont(font)
        self.TITULO_1.setText("")
        self.TITULO_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_1.setObjectName("TITULO_1")
        self.TITULO_2 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_2.setGeometry(QtCore.QRect(120, 110, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_2.setFont(font)
        self.TITULO_2.setText("")
        self.TITULO_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_2.setObjectName("TITULO_2")
        self.TITULO_3 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_3.setGeometry(QtCore.QRect(120, 140, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_3.setFont(font)
        self.TITULO_3.setText("")
        self.TITULO_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_3.setObjectName("TITULO_3")
        self.TITULO_4 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_4.setGeometry(QtCore.QRect(120, 170, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_4.setFont(font)
        self.TITULO_4.setText("")
        self.TITULO_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_4.setObjectName("TITULO_4")
        self.TITULO_5 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_5.setGeometry(QtCore.QRect(120, 200, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_5.setFont(font)
        self.TITULO_5.setText("")
        self.TITULO_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_5.setObjectName("TITULO_5")
        self.TITULO_6 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_6.setGeometry(QtCore.QRect(120, 230, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_6.setFont(font)
        self.TITULO_6.setText("")
        self.TITULO_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_6.setObjectName("TITULO_6")
        self.TITULO_7 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_7.setGeometry(QtCore.QRect(120, 260, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_7.setFont(font)
        self.TITULO_7.setText("")
        self.TITULO_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_7.setObjectName("TITULO_7")
        self.TITULO_8 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_8.setGeometry(QtCore.QRect(120, 290, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_8.setFont(font)
        self.TITULO_8.setText("")
        self.TITULO_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_8.setObjectName("TITULO_8")
        self.TITULO_9 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_9.setGeometry(QtCore.QRect(120, 320, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_9.setFont(font)
        self.TITULO_9.setText("")
        self.TITULO_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_9.setObjectName("TITULO_9")
        self.TITULO_10 = QtWidgets.QLabel(self.centralwidget)
        self.TITULO_10.setGeometry(QtCore.QRect(120, 350, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.TITULO_10.setFont(font)
        self.TITULO_10.setText("")
        self.TITULO_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TITULO_10.setObjectName("TITULO_10")
        self.ATRAS = QtWidgets.QPushButton(self.centralwidget)
        self.ATRAS.setGeometry(QtCore.QRect(130, 10, 41, 31))
        self.ATRAS.setObjectName("ATRAS")
        self.PEDIDOSPENDIENTES = QtWidgets.QLabel(self.centralwidget)
        self.PEDIDOSPENDIENTES.setGeometry(QtCore.QRect(190, 10, 171, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.PEDIDOSPENDIENTES.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.PEDIDOSPENDIENTES.setFont(font)
        self.PEDIDOSPENDIENTES.setObjectName("PEDIDOSPENDIENTES")
        self.NUMPENDIENTES = QtWidgets.QLabel(self.centralwidget)
        self.NUMPENDIENTES.setGeometry(QtCore.QRect(530, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.NUMPENDIENTES.setFont(font)
        self.NUMPENDIENTES.setAlignment(QtCore.Qt.AlignCenter)
        self.NUMPENDIENTES.setObjectName("NUMPENDIENTES")
        self.FILTROCANCELADAS = QtWidgets.QPushButton(self.centralwidget)
        self.FILTROCANCELADAS.setGeometry(QtCore.QRect(220, 420, 81, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(30, 205, 92))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 205, 92))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 205, 92))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.FILTROCANCELADAS.setPalette(palette)
        self.FILTROCANCELADAS.setObjectName("FILTROCANCELADAS")
        self.FILTROPEDIDO = QtWidgets.QPushButton(self.centralwidget)
        self.FILTROPEDIDO.setGeometry(QtCore.QRect(130, 420, 81, 31))
        self.FILTROPEDIDO.setObjectName("FILTROPEDIDO")
        self.CREARCOTIZACION = QtWidgets.QPushButton(self.centralwidget)
        self.CREARCOTIZACION.setGeometry(QtCore.QRect(480, 420, 91, 31))
        self.CREARCOTIZACION.setObjectName("CREARCOTIZACION")
        self.Lista_cotizaciones = QtWidgets.QPushButton(self.centralwidget)
        self.Lista_cotizaciones.setGeometry(QtCore.QRect(580, 420, 111, 31))
        self.Lista_cotizaciones.setObjectName("Lista_cotizaciones")
        self.MOTIVO_4 = QtWidgets.QLabel(self.centralwidget)
        self.MOTIVO_4.setGeometry(QtCore.QRect(620, 170, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.MOTIVO_4.setFont(font)
        self.MOTIVO_4.setText("")
        self.MOTIVO_4.setAlignment(QtCore.Qt.AlignCenter)
        self.MOTIVO_4.setObjectName("MOTIVO_4")
        self.MOTIVO_1 = QtWidgets.QLabel(self.centralwidget)
        self.MOTIVO_1.setGeometry(QtCore.QRect(620, 80, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.MOTIVO_1.setFont(font)
        self.MOTIVO_1.setText("")
        self.MOTIVO_1.setAlignment(QtCore.Qt.AlignCenter)
        self.MOTIVO_1.setObjectName("MOTIVO_1")
        self.MOTIVO_7 = QtWidgets.QLabel(self.centralwidget)
        self.MOTIVO_7.setGeometry(QtCore.QRect(620, 260, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.MOTIVO_7.setFont(font)
        self.MOTIVO_7.setText("")
        self.MOTIVO_7.setAlignment(QtCore.Qt.AlignCenter)
        self.MOTIVO_7.setObjectName("MOTIVO_7")
        self.MOTIVO_2 = QtWidgets.QLabel(self.centralwidget)
        self.MOTIVO_2.setGeometry(QtCore.QRect(620, 110, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.MOTIVO_2.setFont(font)
        self.MOTIVO_2.setText("")
        self.MOTIVO_2.setAlignment(QtCore.Qt.AlignCenter)
        self.MOTIVO_2.setObjectName("MOTIVO_2")
        self.MOTIVO_6 = QtWidgets.QLabel(self.centralwidget)
        self.MOTIVO_6.setGeometry(QtCore.QRect(620, 230, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.MOTIVO_6.setFont(font)
        self.MOTIVO_6.setText("")
        self.MOTIVO_6.setAlignment(QtCore.Qt.AlignCenter)
        self.MOTIVO_6.setObjectName("MOTIVO_6")
        self.MOTIVO_10 = QtWidgets.QLabel(self.centralwidget)
        self.MOTIVO_10.setGeometry(QtCore.QRect(620, 350, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.MOTIVO_10.setFont(font)
        self.MOTIVO_10.setText("")
        self.MOTIVO_10.setAlignment(QtCore.Qt.AlignCenter)
        self.MOTIVO_10.setObjectName("MOTIVO_10")
        self.MOTIVO_8 = QtWidgets.QLabel(self.centralwidget)
        self.MOTIVO_8.setGeometry(QtCore.QRect(620, 290, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.MOTIVO_8.setFont(font)
        self.MOTIVO_8.setText("")
        self.MOTIVO_8.setAlignment(QtCore.Qt.AlignCenter)
        self.MOTIVO_8.setObjectName("MOTIVO_8")
        self.MOTIVO_5 = QtWidgets.QLabel(self.centralwidget)
        self.MOTIVO_5.setGeometry(QtCore.QRect(620, 200, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.MOTIVO_5.setFont(font)
        self.MOTIVO_5.setText("")
        self.MOTIVO_5.setAlignment(QtCore.Qt.AlignCenter)
        self.MOTIVO_5.setObjectName("MOTIVO_5")
        self.MOTIVO_3 = QtWidgets.QLabel(self.centralwidget)
        self.MOTIVO_3.setGeometry(QtCore.QRect(620, 140, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.MOTIVO_3.setFont(font)
        self.MOTIVO_3.setText("")
        self.MOTIVO_3.setAlignment(QtCore.Qt.AlignCenter)
        self.MOTIVO_3.setObjectName("MOTIVO_3")
        self.MOTIVO_9 = QtWidgets.QLabel(self.centralwidget)
        self.MOTIVO_9.setGeometry(QtCore.QRect(620, 320, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.MOTIVO_9.setFont(font)
        self.MOTIVO_9.setText("")
        self.MOTIVO_9.setAlignment(QtCore.Qt.AlignCenter)
        self.MOTIVO_9.setObjectName("MOTIVO_9")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(620, 50, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.FILTROENVIADAS = QtWidgets.QPushButton(self.centralwidget)
        self.FILTROENVIADAS.setGeometry(QtCore.QRect(40, 420, 81, 31))
        self.FILTROENVIADAS.setObjectName("FILTROENVIADAS")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 393, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.PEDIDOSPENDIENTES_2 = QtWidgets.QLabel(self.centralwidget)
        self.PEDIDOSPENDIENTES_2.setGeometry(QtCore.QRect(350, 10, 171, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.PEDIDOSPENDIENTES_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.PEDIDOSPENDIENTES_2.setFont(font)
        self.PEDIDOSPENDIENTES_2.setObjectName("PEDIDOSPENDIENTES_2")
        Gestor_Pedidos.setCentralWidget(self.centralwidget)

        self.retranslateUi(Gestor_Pedidos)
        QtCore.QMetaObject.connectSlotsByName(Gestor_Pedidos)
        Gestor_Pedidos.setTabOrder(self.toolButton, self.toolButton_2)
        Gestor_Pedidos.setTabOrder(self.toolButton_2, self.toolButton_3)
        Gestor_Pedidos.setTabOrder(self.toolButton_3, self.toolButton_4)
        Gestor_Pedidos.setTabOrder(self.toolButton_4, self.toolButton_5)
        Gestor_Pedidos.setTabOrder(self.toolButton_5, self.toolButton_6)
        Gestor_Pedidos.setTabOrder(self.toolButton_6, self.toolButton_7)
        Gestor_Pedidos.setTabOrder(self.toolButton_7, self.toolButton_8)
        Gestor_Pedidos.setTabOrder(self.toolButton_8, self.toolButton_9)
        Gestor_Pedidos.setTabOrder(self.toolButton_9, self.toolButton_10)
        Gestor_Pedidos.setTabOrder(self.toolButton_10, self.ADELANTE)

    def retranslateUi(self, Gestor_Pedidos):
        _translate = QtCore.QCoreApplication.translate
        Gestor_Pedidos.setWindowTitle(_translate("Gestor_Pedidos", "MainWindow"))
        self.toolButton.setText(_translate("Gestor_Pedidos", "1"))
        self.toolButton_2.setText(_translate("Gestor_Pedidos", "2"))
        self.toolButton_3.setText(_translate("Gestor_Pedidos", "3"))
        self.toolButton_4.setText(_translate("Gestor_Pedidos", "4"))
        self.toolButton_5.setText(_translate("Gestor_Pedidos", "5"))
        self.toolButton_6.setText(_translate("Gestor_Pedidos", "6"))
        self.toolButton_7.setText(_translate("Gestor_Pedidos", "7"))
        self.toolButton_8.setText(_translate("Gestor_Pedidos", "8"))
        self.toolButton_9.setText(_translate("Gestor_Pedidos", "9"))
        self.toolButton_10.setText(_translate("Gestor_Pedidos", "10"))
        self.label_2.setText(_translate("Gestor_Pedidos", "TIENDA"))
        self.label_3.setText(_translate("Gestor_Pedidos", "TITULO COTIZACION"))
        self.label_4.setText(_translate("Gestor_Pedidos", "# DE COTIZACION"))
        self.label_5.setText(_translate("Gestor_Pedidos", "ESTATUS"))
        self.label_7.setText(_translate("Gestor_Pedidos", "FECHA COTIZACION"))
        self.ADELANTE.setText(_translate("Gestor_Pedidos", ">>>"))
        self.ATRAS.setText(_translate("Gestor_Pedidos", "<<<"))
        self.PEDIDOSPENDIENTES.setText(_translate("Gestor_Pedidos", "COTIZACIONES"))
        self.NUMPENDIENTES.setText(_translate("Gestor_Pedidos", "9999"))
        self.FILTROCANCELADAS.setText(_translate("Gestor_Pedidos", "CANCELADAS"))
        self.FILTROPEDIDO.setText(_translate("Gestor_Pedidos", "C/PEDIDO"))
        self.CREARCOTIZACION.setText(_translate("Gestor_Pedidos", "Crear Cotizacion"))
        self.Lista_cotizaciones.setText(_translate("Gestor_Pedidos", "Lista Cotizaciones"))
        self.label_6.setText(_translate("Gestor_Pedidos", "MOTIVO"))
        self.FILTROENVIADAS.setText(_translate("Gestor_Pedidos", "ENVIADAS"))
        self.label.setText(_translate("Gestor_Pedidos", "FILTROS BUSQUEDA"))
        self.PEDIDOSPENDIENTES_2.setText(_translate("Gestor_Pedidos", "SEND/CANC/PED"))

        self.FILTROENVIADAS.clicked.connect(self.llenadogui)
        self.ATRAS.clicked.connect(self.atras)
        self.ADELANTE.clicked.connect(self.adelante)
        self.FILTROCANCELADAS.clicked.connect(self.filtrocancelados)
        self.FILTROPEDIDO.clicked.connect(self.filtropedidos)
        self.Lista_cotizaciones.clicked.connect(self.abrirlistacotizacion)

        self.toolButton.clicked.connect(self.tomarNUMCOT_boton_1)
        self.toolButton_2.clicked.connect(self.tomarNUMCOT_boton_2)
        self.toolButton_3.clicked.connect(self.tomarNUMCOT_boton_3)
        self.toolButton_4.clicked.connect(self.tomarNUMCOT_boton_4)
        self.toolButton_5.clicked.connect(self.tomarNUMCOT_boton_5)
        self.toolButton_6.clicked.connect(self.tomarNUMCOT_boton_6)
        self.toolButton_7.clicked.connect(self.tomarNUMCOT_boton_7)
        self.toolButton_8.clicked.connect(self.tomarNUMCOT_boton_8)
        self.toolButton_9.clicked.connect(self.tomarNUMCOT_boton_9)
        self.toolButton_10.clicked.connect(self.tomarNUMCOT_boton_10)
        self.CREARCOTIZACION.clicked.connect(self.abrircotizador)




    def llenadogui(self):
        vec=consultarfiltro()
        globals()["vectorglobal"] = vec
        #print(globals()["vectorglobal"])
        self.LLENARVALORES(vec)
        self.NUMPENDIENTES.setText(str(len(vec)))
        self.PEDIDOSPENDIENTES_2.setText("ENVIADAS ------>")
        return()

    def filtropedidos(self):
        vec = consultarfiltro_PEDIDOS()
        globals()["vectorglobal"] = vec
        self.LLENARVALORES(vec)
        self.NUMPENDIENTES.setText(str(len(vec)))
        self.PEDIDOSPENDIENTES_2.setText("CON PEDIDOS ->")
        return()

    def filtrocancelados(self):
        vec=consultarfiltro_CANCELADOS()
        globals()["vectorglobal"] = vec
        self.LLENARVALORES(vec)
        self.NUMPENDIENTES.setText(str(len(vec)))
        self.PEDIDOSPENDIENTES_2.setText("CANCELADAS ------->")
        return()

    def adelante(self):
        s = globals()["pagina"]
        pag = int(s + 10)

        globals()["pagina"] = pag
        vector = globals()["vectorglobal"]
        self.LLENARVALORES(vector)

    # mover hacia ATRAS
    def atras(self):
        s = globals()["pagina"]
        if s < 9:
            print("no puedo retroceder más")
            return ()
        else:
            pag = int(s - 10)
            globals()["pagina"] = pag
            vector = globals()["vectorglobal"]
            self.LLENARVALORES(vector)

    def LLENARVALORES(self, info):
        self.limpiar()
        vector = info
        pag = globals()["pagina"]
        globals()["vectorglobal"] = vector
        #print("---> GLOBALS")
        longitudvector = len(vector)
        #print("tamaño vector-> ",longitudvector)

        # posición del vector
        a1 = 0
        a2 = 1
        a3 = 2
        a4 = 3
        a5 = 4
        a6 = 5
        a7 = 7
        a8 = 8
        # posición de la pagina
        com1 = int(pag)
        com2 = int(pag + 1)
        com3 = int(pag + 2)
        com4 = int(pag + 3)
        com5 = int(pag + 4)
        com6 = int(pag + 5)
        com7 = int(pag + 6)
        com8 = int(pag + 7)
        com9 = int(pag + 8)
        com10 = int(pag + 9)

        if longitudvector == 0:
            print("no hay consultas")
            return ()
        if longitudvector > com1:

            pos = pag
            self.toolButton.setText(str(pos))
            self.toolButton.setEnabled(1)
            self.TIENDA_1.setText(str(vector[pos][a1]))
            self.TITULO_1.setText(vector[pos][a2])
            self.COT_1.setText(vector[pos][a3])

            self.STATS_1.setText(self.estatus(int(vector[pos][a4])))
            self.MOTIVO_1.setText(self.motivo(int(vector[pos][a5])))
            self.FECHA_1.setText(convertirFECHA(str(vector[pos][a6])))
        if longitudvector > com2:
            #print("entrando longitudvector")
            pos = pag+1
            self.toolButton_2.setText(str(pos))
            self.toolButton_2.setEnabled(1)
            self.TIENDA_2.setText(str(vector[pos][a1]))
            self.TITULO_2.setText(vector[pos][a2])
            self.COT_2.setText(vector[pos][a3])
            self.STATS_2.setText(self.estatus(int(vector[pos][a4])))
            self.MOTIVO_2.setText(self.motivo(int(vector[pos][a5])))
            self.FECHA_2.setText(convertirFECHA(str(vector[pos][a6])))
        if longitudvector > com3:
            #print("entrando longitudvector")
            pos = pag+2
            self.toolButton_3.setText(str(pos))
            self.toolButton_3.setEnabled(1)
            self.TIENDA_3.setText(str(vector[pos][a1]))
            self.TITULO_3.setText(vector[pos][a2])
            self.COT_3.setText(vector[pos][a3])
            self.STATS_3.setText(self.estatus(int(vector[pos][a4])))
            self.MOTIVO_3.setText(self.motivo(int(vector[pos][a5])))
            self.FECHA_3.setText(convertirFECHA(str(vector[pos][a6])))
        if longitudvector > com4:
            #print("entrando longitudvector")
            pos = pag+3
            self.toolButton_4.setText(str(pos))
            self.toolButton_4.setEnabled(1)
            self.TIENDA_4.setText(str(vector[pos][a1]))
            self.TITULO_4.setText(vector[pos][a2])
            self.COT_4.setText(vector[pos][a3])
            self.STATS_4.setText(self.estatus(int(vector[pos][a4])))
            self.MOTIVO_4.setText(self.motivo(int(vector[pos][a5])))
            self.FECHA_4.setText(convertirFECHA(str(vector[pos][a6])))
        if longitudvector > com5:
            #print("entrando longitudvector")
            pos = pag+4
            self.toolButton_5.setText(str(pos))
            self.toolButton_5.setEnabled(1)
            self.TIENDA_5.setText(str(vector[pos][a1]))
            self.TITULO_5.setText(vector[pos][a2])
            self.COT_5.setText(vector[pos][a3])
            self.STATS_5.setText(self.estatus(int(vector[pos][a4])))
            self.MOTIVO_5.setText(self.motivo(int(vector[pos][a5])))
            self.FECHA_5.setText(convertirFECHA(str(vector[pos][a6])))
        if longitudvector > com6:
            #print("entrando longitudvector")
            pos = pag+5
            self.toolButton_6.setText(str(pos))
            self.toolButton_6.setEnabled(1)
            self.TIENDA_6.setText(str(vector[pos][a1]))
            self.TITULO_6.setText(vector[pos][a2])
            self.COT_6.setText(vector[pos][a3])
            self.STATS_6.setText(self.estatus(int(vector[pos][a4])))
            self.MOTIVO_6.setText(self.motivo(int(vector[pos][a5])))
            self.FECHA_6.setText(convertirFECHA(str(vector[pos][a6])))
        if longitudvector > com7:
            #print("entrando longitudvector")
            pos = pag+6
            self.toolButton_7.setText(str(pos))
            self.toolButton_7.setEnabled(1)
            self.TIENDA_7.setText(str(vector[pos][a1]))
            self.TITULO_7.setText(vector[pos][a2])
            self.COT_7.setText(vector[pos][a3])
            self.STATS_7.setText(self.estatus(int(vector[pos][a4])))
            self.MOTIVO_7.setText(self.motivo(int(vector[pos][a5])))
            self.FECHA_7.setText(convertirFECHA(str(vector[pos][a6])))
        if longitudvector > com8:
            #print("entrando longitudvector")
            pos = pag+7
            self.toolButton_8.setText(str(pos))
            self.toolButton_8.setEnabled(1)
            self.TIENDA_8.setText(str(vector[pos][a1]))
            self.TITULO_8.setText(vector[pos][a2])
            self.COT_8.setText(vector[pos][a3])
            self.STATS_8.setText(self.estatus(int(vector[pos][a4])))
            self.MOTIVO_8.setText(self.motivo(int(vector[pos][a5])))
            self.FECHA_8.setText(convertirFECHA(str(vector[pos][a6])))
        if longitudvector > com9:
            #print("entrando longitudvector")
            pos = pag+8
            self.toolButton_9.setText(str(pos))
            self.toolButton_9.setEnabled(1)
            self.TIENDA_9.setText(str(vector[pos][a1]))
            self.TITULO_9.setText(vector[pos][a2])
            self.COT_9.setText(vector[pos][a3])
            self.STATS_9.setText(self.estatus(int(vector[pos][a4])))
            self.MOTIVO_9.setText(self.motivo(int(vector[pos][a5])))
            self.FECHA_9.setText(convertirFECHA(str(vector[pos][a6])))
        if longitudvector > com10:
            #print("entrando longitudvector")
            pos = pag+9
            self.toolButton_10.setText(str(pos))
            self.toolButton_10.setEnabled(1)
            self.TIENDA_10.setText(str(vector[pos][a1]))
            self.TITULO_10.setText(vector[pos][a2])
            self.COT_10.setText(vector[pos][a3])
            self.STATS_10.setText(self.estatus(int(vector[pos][a4])))
            self.MOTIVO_10.setText(self.motivo(int(vector[pos][a5])))
            self.FECHA_10.setText(convertirFECHA(str(vector[pos][a6])))

        return ()

    def estatus(self,posicion):
        if posicion==0:
            estatus="ENVIADO"
            return(estatus)
        if posicion==1:
            estatus="PEDIDO"
            return(estatus)
        if posicion==2:
            estatus="CANCELADO"
            return(estatus)

    def motivo(self,posicion):
        if posicion==0:
            motivo="N/A"
            return(motivo)
        if posicion==1:
            motivo="Precio Alto"
            return(motivo)
        if posicion==2:
            motivo="Retraso COT"
            return(motivo)
        if posicion==3:
            motivo="pro/iguala"
            return(motivo)
        if posicion==4:
            motivo="NO instalacion"
            return(motivo)
        if posicion==5:
            motivo="Tiempo Entrega"
            return(motivo)
        if posicion==6:
            motivo="OTROS"
            return(motivo)
        return()

    def limpiar(self):
        act = 0

        self.toolButton.setText("...")
        self.toolButton.setEnabled(act)
        self.TIENDA_1.setText("")
        self.TITULO_1.setText("")
        self.COT_1.setText("")
        self.STATS_1.setText("")
        self.MOTIVO_1.setText("")
        self.FECHA_1.setText("")

        self.toolButton_2.setText("...")
        self.toolButton_2.setEnabled(act)
        self.TIENDA_2.setText("")
        self.TITULO_2.setText("")
        self.COT_2.setText("")
        self.STATS_2.setText("")
        self.MOTIVO_2.setText("")
        self.FECHA_2.setText("")

        self.toolButton_3.setText("...")
        self.toolButton_3.setEnabled(act)
        self.TIENDA_3.setText("")
        self.TITULO_3.setText("")
        self.COT_3.setText("")
        self.STATS_3.setText("")
        self.MOTIVO_3.setText("")
        self.FECHA_3.setText("")

        self.toolButton_4.setText("...")
        self.toolButton_4.setEnabled(act)
        self.TIENDA_4.setText("")
        self.TITULO_4.setText("")
        self.COT_4.setText("")
        self.STATS_4.setText("")
        self.MOTIVO_4.setText("")
        self.FECHA_4.setText("")

        self.toolButton_5.setText("...")
        self.toolButton_5.setEnabled(act)
        self.TIENDA_5.setText("")
        self.TITULO_5.setText("")
        self.COT_5.setText("")
        self.STATS_5.setText("")
        self.MOTIVO_5.setText("")
        self.FECHA_5.setText("")

        self.toolButton_6.setText("...")
        self.toolButton_6.setEnabled(act)
        self.TIENDA_6.setText("")
        self.TITULO_6.setText("")
        self.COT_6.setText("")
        self.STATS_6.setText("")
        self.MOTIVO_6.setText("")
        self.FECHA_6.setText("")

        self.toolButton_7.setText("...")
        self.toolButton_7.setEnabled(act)
        self.TIENDA_7.setText("")
        self.TITULO_7.setText("")
        self.COT_7.setText("")
        self.STATS_7.setText("")
        self.MOTIVO_7.setText("")
        self.FECHA_7.setText("")

        self.toolButton_8.setText("...")
        self.toolButton_8.setEnabled(act)
        self.TIENDA_8.setText("")
        self.TITULO_8.setText("")
        self.COT_8.setText("")
        self.STATS_8.setText("")
        self.MOTIVO_8.setText("")
        self.FECHA_8.setText("")

        self.toolButton_9.setText("...")
        self.toolButton_9.setEnabled(act)
        self.TIENDA_9.setText("")
        self.TITULO_9.setText("")
        self.COT_9.setText("")
        self.STATS_9.setText("")
        self.MOTIVO_9.setText("")
        self.FECHA_9.setText("")

        self.toolButton_10.setText("...")
        self.toolButton_10.setEnabled(act)
        self.TIENDA_10.setText("")
        self.TITULO_10.setText("")
        self.COT_10.setText("")
        self.STATS_10.setText("")
        self.MOTIVO_10.setText("")
        self.FECHA_10.setText("")

        return()

    def detallecotizacion(self,cot):
        Dialog = QtWidgets.QDialog()
        # enviar datos al form DIALOG
        # self.m = seccion  # "HOLA desde el primero form"
        ui = Ui_Dialog_visor_cotizador()
        ui.setupUi(Dialog)
        #cot = "12-15122019-CV-1"
        ui.visor_cotizacion(cot)
        Dialog.show()
        respuesta = Dialog.exec_()

        if respuesta == QtWidgets.QDialog.Accepted:
            print("Boton aceptado del VISOR COTIZACION")
            self.llenadogui()
        else:
            print("Boton cancelado")
        return ()


    def tomarNUMCOT_boton_1(self):
        #BOTÓN 1
        numcot=self.COT_1.text()
        self.detallecotizacion(numcot)
        return()
    def tomarNUMCOT_boton_2(self):
        #BOTÓN 2
        numcot=self.COT_2.text()
        self.detallecotizacion(numcot)

        return()
    def tomarNUMCOT_boton_3(self):
        #BOTÓN 3
        numcot=self.COT_3.text()
        self.detallecotizacion(numcot)
        return()
    def tomarNUMCOT_boton_4(self):
        #BOTÓN 4
        numcot=self.COT_4.text()
        self.detallecotizacion(numcot)
        return()
    def tomarNUMCOT_boton_5(self):
        #BOTÓN 5
        numcot=self.COT_5.text()
        self.detallecotizacion(numcot)
        return()
    def tomarNUMCOT_boton_6(self):
        #BOTÓN 6
        numcot=self.COT_6.text()
        self.detallecotizacion(numcot)
        return()
    def tomarNUMCOT_boton_7(self):
        #BOTÓN 7
        numcot=self.COT_7.text()
        self.detallecotizacion(numcot)
        return()
    def tomarNUMCOT_boton_8(self):
        #BOTÓN 8
        numcot=self.COT_8.text()
        self.detallecotizacion(numcot)
        return()
    def tomarNUMCOT_boton_9(self):
        #BOTÓN 9
        numcot=self.COT_9.text()
        self.detallecotizacion(numcot)
        return()
    def tomarNUMCOT_boton_10(self):
        #BOTÓN 10
        numcot=self.COT_10.text()
        self.detallecotizacion(numcot)
        return()

# filtro cancelados
def consultarfiltro_CANCELADOS():
    print("FILTRANDO")
    basedatos="administrativo.db"
    record=[]
    try:
        sqliteConnection = sqlite3.connect(basedatos)
        cursor = sqliteConnection.cursor()
        #print("Successfully Connected to SQLite")
        SELECT = """
                SELECT 
                numtienda, titulocotizacion, numcotizacion, estatus,
                motivo, timestampcreacion
                FROM
                cotizaciones

                WHERE
                estatus = 2
                """
        cursor.execute(SELECT)
        record = cursor.fetchall()
        cursor.close

    except sqlite3.Error as error:
        print("Error, ALV -----> ", error)
    finally:
        if (sqliteConnection):
            sqliteConnection.close()
            print("Cerrando conexión de Base de Datos")
            #print(record)
    return (record)


#filtro PEDIDOS
def consultarfiltro_PEDIDOS():
    print("FILTRANDO")
    basedatos="administrativo.db"
    record=[]
    try:
        sqliteConnection = sqlite3.connect(basedatos)
        cursor = sqliteConnection.cursor()
        #print("Successfully Connected to SQLite")
        SELECT = """
                SELECT 
                numtienda, titulocotizacion, numcotizacion, estatus,
                motivo, timestampcreacion
                FROM
                cotizaciones

                WHERE
                estatus = 1
                """
        cursor.execute(SELECT)
        record = cursor.fetchall()
        cursor.close

    except sqlite3.Error as error:
        print("Error, ALV -----> ", error)
    finally:
        if (sqliteConnection):
            sqliteConnection.close()
            print("Cerrando conexión de Base de Datos")
            #print(record)
    return (record)

#filtro de ENVIADAS
def consultarfiltro():
    print("FILTRANDO")
    basedatos="administrativo.db"
    record=[]
    try:
        sqliteConnection = sqlite3.connect(basedatos)
        cursor = sqliteConnection.cursor()
        #print("Successfully Connected to SQLite")
        SELECT = """
                SELECT 
                numtienda, titulocotizacion, numcotizacion, estatus,
                motivo, timestampcreacion
                FROM
                cotizaciones

                WHERE
                estatus = 0
                """
        cursor.execute(SELECT)
        record = cursor.fetchall()
        cursor.close

    except sqlite3.Error as error:
        print("Error, ALV -----> ", error)
    finally:
        if (sqliteConnection):
            sqliteConnection.close()
            print("Cerrando conexión de Base de Datos")
            #print(record)
    return (record)

def convertirFECHA(tiempo):
    fecha=time.strftime("%D ", time.localtime(int(tiempo)))
    return(fecha)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Gestor_Pedidos = QtWidgets.QMainWindow()
    ui = Ui_Gestor_Cot()
    ui.setupUi_GESTORCOTIZACIONES(Gestor_Pedidos)
    Gestor_Pedidos.show()
    ui.llenadogui()
    sys.exit(app.exec_())
